/*
 * @Author: kingweicai 
 * @Date: 2019-05-16 16:18:46 
 * @Last Modified by: kingweicai
 * @Last Modified time: 2019-06-27 23:24:39
 */
 const path = require('path');

 const testSuit = {
   name: 'suit73',
   compilerConfig: {
    //  cmd: ['-d', '-cc', '2>_<1087./page/API/components/set-tab-bar/set-tab-bar.wxml>_<10870>_<1087./page/API/index.wxml>_<10871>_<1087set-tab-bar --split >_<1087', "--split", ">_<1087", '-gn', '$gwx'],
    //  cmd: ['-d', '-xc', '2>_<1087./page/API/components/set-tab-bar/set-tab-bar.wxml>_<10870>_<1087./page/API/index.wxml>_<10871>_<1087set-tab-bar --split >_<1087', "--split", ">_<1087", '-gn', '$gwx'],
     cmd: ['-d', '-cc', '0', '-gn', '$gwx'],
    //  cmd: ['-d', '-xc', '0', '-gn', '$gwx'],
     'FILESBASE': path.join(__dirname, './proj'),
     outputDir: path.join(__dirname, './out'),
     'FILES': [
       "./page/API/components/set-tab-bar/set-tab-bar.wxml",
       "./page/API/index.wxml",
       "./page/API/pages/action-sheet/action-sheet.wxml",
       "./page/API/pages/add-contact/add-contact.wxml",
       "./page/API/pages/animation/animation.wxml",
       "./page/API/pages/background-audio/background-audio.wxml",
       "./page/API/pages/bluetooth/bluetooth.wxml",
       "./page/API/pages/canvas/canvas.wxml",
       "./page/API/pages/capture-screen/capture-screen.wxml",
       "./page/API/pages/choose-address/choose-address.wxml",
       "./page/API/pages/choose-invoice-title/choose-invoice-title.wxml",
       "./page/API/pages/choose-location/choose-location.wxml",
       "./page/API/pages/clipboard-data/clipboard-data.wxml",
       "./page/API/pages/custom-message/custom-message.wxml",
       "./page/API/pages/custom-service/custom-service.wxml",
       "./page/API/pages/doc-web-view/doc-web-view.wxml",
       "./page/API/pages/download-file/download-file.wxml",
       "./page/API/pages/file/file.wxml",
       "./page/API/pages/get-location/get-location.wxml",
       "./page/API/pages/get-network-type/get-network-type.wxml",
       "./page/API/pages/get-system-info/get-system-info.wxml",
       "./page/API/pages/get-user-info/get-user-info.wxml",
       "./page/API/pages/get-wxml-node-info/get-wxml-node-info.wxml",
       "./page/API/pages/ibeacon/ibeacon.wxml",
       "./page/API/pages/image/image.wxml",
       "./page/API/pages/intersection-observer/intersection-observer.wxml",
       "./page/API/pages/load-font-face/load-font-face.wxml",
       "./page/API/pages/login/login.wxml",
       "./page/API/pages/make-phone-call/make-phone-call.wxml",
       "./page/API/pages/modal/modal.wxml",
       "./page/API/pages/navigation-bar-loading/navigation-bar-loading.wxml",
       "./page/API/pages/navigator/navigator.wxml",
       "./page/API/pages/on-accelerometer-change/on-accelerometer-change.wxml",
       "./page/API/pages/on-compass-change/on-compass-change.wxml",
       "./page/API/pages/on-network-status-change/on-network-status-change.wxml",
       "./page/API/pages/open-location/open-location.wxml",
       "./page/API/pages/page-scroll/page-scroll.wxml",
       "./page/API/pages/pull-down-refresh/pull-down-refresh.wxml",
       "./page/API/pages/request/request.wxml",
       "./page/API/pages/request-payment/request-payment.wxml",
       "./page/API/pages/scan-code/scan-code.wxml",
       "./page/API/pages/screen-brightness/screen-brightness.wxml",
       "./page/API/pages/sendMessage/sendMessage.wxml",
       "./page/API/pages/set-navigation-bar-title/set-navigation-bar-title.wxml",
       "./page/API/pages/setting/setting.wxml",
       "./page/API/pages/share/share.wxml",
       "./page/API/pages/share-button/share-button.wxml",
       "./page/API/pages/soter-authentication/soter-authentication.wxml",
       "./page/API/pages/storage/storage.wxml",
       "./page/API/pages/template-message/template-message.wxml",
       "./page/API/pages/toast/toast.wxml",
       "./page/API/pages/upload-file/upload-file.wxml",
       "./page/API/pages/vibrate/vibrate.wxml",
       "./page/API/pages/video/video.wxml",
       "./page/API/pages/voice/voice.wxml",
       "./page/API/pages/web-socket/web-socket.wxml",
       "./page/API/pages/wifi/wifi.wxml",
       "./page/API/pages/worker/worker.wxml",
       "./page/cloud/index.wxml",
       "./page/cloud/pages/cloud-file-component/cloud-file-component.wxml",
       "./page/cloud/pages/crud/crud.wxml",
       "./page/cloud/pages/crud-detail/crud-detail.wxml",
       "./page/cloud/pages/db-permission/db-permission.wxml",
       "./page/cloud/pages/delete-file/delete-file.wxml",
       "./page/cloud/pages/doc-web-view/doc-web-view.wxml",
       "./page/cloud/pages/download-file/download-file.wxml",
       "./page/cloud/pages/get-temp-file-url/get-temp-file-url.wxml",
       "./page/cloud/pages/get-wx-context/get-wx-context.wxml",
       "./page/cloud/pages/scf-database/scf-database.wxml",
       "./page/cloud/pages/scf-openapi/scf-openapi.wxml",
       "./page/cloud/pages/scf-storage/scf-storage.wxml",
       "./page/cloud/pages/server-date/server-date.wxml",
       "./page/cloud/pages/upload-file/upload-file.wxml",
       "./page/cloud/pages/user-authentication/user-authentication.wxml",
       "./page/common/foot.wxml","./page/common/head.wxml",
       "./page/component/index.wxml",
       "./page/component/pages/ad/ad.wxml",
       "./page/component/pages/audio/audio.wxml",
       "./page/component/pages/button/button.wxml",
       "./page/component/pages/camera/camera.wxml",
       "./page/component/pages/camera-scan-code/camera-scan-code.wxml",
       "./page/component/pages/canvas/canvas.wxml",
       "./page/component/pages/checkbox/checkbox.wxml",
       "./page/component/pages/cover-view/cover-view.wxml",
       "./page/component/pages/doc-web-view/doc-web-view.wxml",
       "./page/component/pages/editor/editor.wxml",
       "./page/component/pages/form/form.wxml",
       "./page/component/pages/icon/icon.wxml",
       "./page/component/pages/image/image.wxml",
       "./page/component/pages/input/input.wxml",
       "./page/component/pages/label/label.wxml",
       "./page/component/pages/map/map.wxml",
       "./page/component/pages/map-styles/map-styles.wxml",
       "./page/component/pages/movable-view/movable-view.wxml",
       "./page/component/pages/navigator/navigate.wxml",
       "./page/component/pages/navigator/navigator.wxml",
       "./page/component/pages/navigator/redirect.wxml",
       "./page/component/pages/open-data/open-data.wxml",
       "./page/component/pages/picker/picker.wxml",
       "./page/component/pages/picker-view/picker-view.wxml",
       "./page/component/pages/progress/progress.wxml",
       "./page/component/pages/radio/radio.wxml",
       "./page/component/pages/rich-text/rich-text.wxml",
       "./page/component/pages/scroll-view/scroll-view.wxml",
       "./page/component/pages/slider/slider.wxml",
       "./page/component/pages/swiper/swiper.wxml",
       "./page/component/pages/switch/switch.wxml",
       "./page/component/pages/text/text.wxml",
       "./page/component/pages/textarea/textarea.wxml",
       "./page/component/pages/video/video.wxml",
       "./page/component/pages/view/view.wxml",
       "./page/component/pages/web-view/web-view.wxml"
     ]
   },
   units: [{
     name: './page/API/index.wxml',
     renderPath: './page/API/index.wxml',
     renderData: function () {
       let env = {};
       let dd = {};
       let global = {};
       return {
         env: env,
         dd: dd,
         global: global
       };
     },
     global: {}
   }]
 };
 
 module.exports = testSuit;