export const WORKER_GLOBAL_ERROR = 11;
export const RENDER_GLOBAL_ERROR = 12;
export const REGISTER_WORKER_ERROR = 13;
export const CUSTOM_WORKER_ERROR = 14;

// WORKER_GLOBAL_ERROR,
// RENDER_GLOBAL_ERROR,
// REGISTER_WORKER_ERROR,
// CUSTOM_WORKER_ERROR,
