export enum CustomEvent {
  INIT_DATA_READY = 'INIT_DATA_READY',
  APP_DATA_CHANGE = 'APP_DATA_CHANGE',
  PAGE_EVENT = 'PAGE_EVENT',
  COMPONENT_DATA_CHANGE = 'COMPONENT_DATA_CHANGE',
  COMPONENT_EVENT = 'COMPONENT_EVENT',
  PAGE_READY = 'PAGE_READY',
  PAGE_SHOW = 'PAGE_SHOW'
}

export enum NativeEvent {
 DOCUMENT_READY = 'DocumentReady'
}
