const lang_ZH = {
  "OA_index_share_title":'OA小程序',
  "OA_index_share_content": '点击进入oa小程序',

  "OA_Form_Detail_Residue":'残值',
  "OA_no_message": "数据为空",
  "OA_loading_text": "加载中...",
  "OA_index_link_waitapproval": "待审批",
  "OA_index_link_submitted": "已提交",
  "OA_index_link_reimbursement": "费用报销",
  "OA_index_link_businesstravel": "差旅报销",
  "OA_index_link_budget": "预算统计",
  "OA_index_link_authorize": "授权",
  "OA_index_link_taxnumber": "财务税号",

  "OA_index_alert_authorization": "您没有权限查看该报表",
  "OA_index_alert_network": "网络异常",
  "OA_index_alert_data": "数据异常",
  "OA_index_alert_confirm": "确定",
  "OA_index_alert_prompt": "提示",


  "OA_notice_title_my_taxnumber": "我的财务税号",
  "OA_notice_title_taxnumber": "财务税号",
  "OA_notice_text_company": "公司：",
  "OA_notice_text_taxnumber": "税号：",
  "OA_notice_text_bankaccount": "银行帐号：",
  "OA_notice_text_bankname": "银行名称：",
  "OA_notice_text_telephone": "电话：",
  "OA_notice_text_address": "地址：",

  "OA_formlist_btn_my_approval": "我审批的",
  "OA_formlist_btn_my_submitted": "我提交的",
  "OA_formlist_btn_waitapproval": "待审批",
  "OA_formlist_btn_approved": "已审批",
  "OA_formlist_btn_submitted": "已提交",
  "OA_formlist_btn_orderbytime": "时间排序",
  "OA_formlist_btn_orderbytype": "类别排序",
  "OA_formlist_btn_orderbysubmitter": "提交人排序",
  "OA_formlist_btn_orderbypriority": "优先级排序",
  "OA_formlist_btn_priority": "排序",
  "OA_formlist_btn_cancel": "取消",
  "OA_formlist_btn_search": "搜索",
  "OA_formlist_btn_approving": "审",
  "OA_formlist_text_counts": "最多显示50条",
  "OA_formlist_OA_number": "报销单号",
  "OA_formlist_OA_data_submit": "提交时间",


  "OA_formlist_text_prompt_submit": "近三个月你还没有提交过哦",
  "OA_formlist_text_prompt": "近3个月没有您的审批单哟",
  "OA_formlist_text_noapproval": "没有待审批申请",
  "OA_oaFormList_alert_network": "网络异常",
  "OA_oaFormList_alert_prompt": "提示",
  "OA_oaFormList_alert_confirm": "确定",
  "OA_oaFormList_alert_effect": "生效",
  "OA_oaFormList_alert_refused": "拒绝",
  "OA_formlist_btn_searchdetail": "主题/提交人/编号搜索",
  "OA_formlist_btn_refresh": "下拉刷新...",


  "OA_costaccount_text_fill": "填写费用报销单",
  "OA_costaccount_text_basic_information": "基础信息",
  "OA_costaccount_text_account_information": "账号信息",
  "OA_costaccount_text_travel_information": "出差信息",
  "OA_costaccount_text_formtype": "表单类型",
  "OA_costaccount_text_unit": "机构",
  "OA_costaccount_text_budgettype": "预算类型",
  "OA_costaccount_text_costcenter": "费用中心",
  "OA_costaccount_text_paymentcompany": "付款公司",
  "OA_costaccount_text_payee": "收款人",
  "OA_costaccount_text_receiptaccount": "收款帐号",
  "OA_costaccount_text_receiptaccount_tip": "请输入收款银行账号",
  "OA_costaccount_text_bankname": "开户行名称",
  "OA_costaccount_text_bankname_tip": "请输入开户行名称",
  "OA_costaccount_text_cityofbank": "开户行所在城市",
  "OA_costaccount_text_cityofbank_tip": "请输入开户行所在城市",
  "OA_costaccount_text_number_invoices": "请填写发票张数",
  "OA_costaccount_text_numberofinvoice": "发票张数",
  "OA_costaccount_text_Apportionmentmonth": "分摊月份",
  "OA_costaccount_text_budgetclassification": "预算分类",
  "OA_costaccount_text_remarks": "备注",
  "OA_costaccount_text_next": "下一步",
  "OA_costaccount_text_prompt": "手机端只支持单费用中心，单预算分类，不跨月的费用报销单",
  "OA_costaccount_text_limited": "限制最多800个字符",

  "OA_Newcostaccount_alert_fill": "注意带 * 为必填项！",
  "OA_Newcostaccount_alert_invoice": "发票张数必须是正整数！",
  "OA_Newcostaccount_text_formtype": "费用报销单",
  "OA_Newcostaccount_text_costcenterorbudgettype": "单费用中心/单预算分类",
  "OA_Newcostaccount_alert_network": "网络异常",
  "OA_Newcostaccount_alert_prompt": "提示",
  "OA_Newcostaccount_alert_confirm": "确定",
  "OA_additemdetail_text_itemdetail": "项目明细",
  "OA_recipient_item_detail": "收款单位账户信息",
  "OA_itemDetail_text_recipientAccountNumber": "收款单位（人）账号",


  "OA_additemdetail_btn_add": "添加",
  "OA_additemdetail_text_itemdetailtotalamount": "项目总金额",
  "OA_additemdetail_text_item": "项目",
  "OA_additemdetail_text_date": "日期",
  "OA_additemdetail_text_amount": "金额",
  "OA_additemdetail_text_explanation": "说明",
  "OA_additemdetail_content_prompt": "暂没有项目明细，请先添加",
  "OA_additemdetail_btn_back": "上一步",
  "OA_additemdetail_btn_submit": "提交",
  "OA_additemdetail_btn_submitting": "提交中...",
  "OA_AddItemDetail_alert_fill": "注意带 * 为必填项！",
  "OA_AddItemDetail_alert_AddPrompt": "提示",
  "OA_AddItemDetail_alert_cancel": "取消",
  "OA_AddItemDetail_alert_confirm": "确认",
  "OA_AddItemDetail_alert_addsucessful": "添加成功",
  "OA_AddItemDetail_alert_network": "网络异常",
  "OA_AddItemDetail_alert_ConfirmSubmit": "确认提交",
  "OA_AddItemDetail_alert_ConfirmSubmit_Error": "提交失败",
  "OA_AddItemDetail_alert_FormatofAmount": "您填写的金额格式不正确！",
  "OA_AddItemDetail_alert_Confirmdelete": "确认删除？",
  "OA_AddItemDetail_alert_Prompt": "提示",


  "OA_itemDetailModal_text_itemdetail": "项目明细",
  "OA_itemDetailModal_text_item": "项目",
  "OA_itemDetailModal_text_startdate": "开始日期",
  "OA_itemDetailModal_text_amount": "金额",
  "OA_itemDetailModal_text_explanation": "说明",
  "OA_itemDetailModal_btn_add": "添加",
  "OA_itemDetailModal_btn_select": "请选择",
  "OA_itemDetailModal_btn_choose": "请选择",
  "OA_itemDetailModal_text_limited": "限制最多800字",


  "OA_travelaccount_text_prompt": "手机端只支持单费用中心，单预算分类，不跨月的报销单",
  "OA_travelaccount_text_select": "请选择",
  "OA_travelaccount_text_formtype": "表单类型",
  "OA_travelaccount_text_unit": "机构",
  "OA_travelaccount_text_budgettype": "预算类型",
  "OA_travelaccount_text_costcenter": "费用中心",
  "OA_travelaccount_text_paymentcompany": "付款公司",
  "OA_travelaccount_text_startdate": "出差开始时间",
  "OA_travelaccount_text_enddate": "出差结束时间",
  "OA_travelaccount_text_address": "出差地点",
  "OA_travelaccount_text_address_place": "请输入出差地点",
  "OA_travelaccount_text_reason": "事由",
  "OA_travelaccount_text_payee": "收款人",
  "OA_travelaccount_text_payee_name": "请输入收款人姓名",
  "OA_travelaccount_text_receiptaccount": "收款帐号",
  "OA_travelaccount_text_bankname": "开户行名称",
  "OA_travelaccount_text_cityofbank": "开户行所在城市",
  "OA_travelaccount_text_numberofinvoice": "发票张数",
  "OA_travelaccount_text_Apportionmentmonth": "分摊月份",
  "OA_travelaccount_text_budgetclassification": "预算分类",
  "OA_travelaccount_text_select_budgettype": "预算类型查询",
  "OA_travelaccount_text_company_inquiry": "公司查询",
  "OA_travelaccount_text_remarks": "备注",
  "OA_travelaccount_text_next": "下一步",


  "OA_travelItem_text_itemdetail": "项目明细",
  "OA_travelItem_btn_add": "添加",
  "OA_travelItem_text_ItemdetailtotalAmount": "项目明细总金额",
  "OA_travelItem_text_item": "项目",
  "OA_travelItem_text_amount": "金额",
  "OA_travelItem_text_explanation": "说明",
  "OA_travelItem_text_prompt": "暂没有项目明细，请先添加",
  "OA_travelItem_btn_back": "上一步",
  "OA_travelItem_btn_submit": "提交",
  "OA_travelitemDetailModal_text_itemdetail": "项目明细",
  "OA_travelitemDetailModal_text_item": "项目",
  "OA_travelitemDetailModal_text_choose": "请选择",
  "OA_travelitemDetailModal_text_Amount": "金额",
  "OA_travelitemDetailModal_text_explanation": "说明",
  "OA_travelitemDetailModal_btn_add": "添加",
  "OA_travelaccount_text_fill": "差旅报销单",
  "OA_NewtravelAccount_alert_date": "开始时间必须小于结束时间！",
  "OA_NewtravelAccount_alert_warning": "警告",
  "OA_NewtravelAccount_alert_fill": "注意带 * 为必填项！",
  "OA_NewtravelAccount_text_formtype": "差旅报销单",
  "OA_NewtravelAccount_text_costcenterorbudgettype": "单费用中心/单预算分类",
  "OA_NewtravelAccount_alert_network": "网络异常",
  "OA_NewtravelAccount_alert_prompt": "提示",
  "OA_NewtravelAccount_alert_confirm": "确定",
  "OA_NewtravelItem_alert_added": "你已经添加过该项目",
  "OA_NewtravelItem_alert_itemdetail": "请添加明细",
  "OA_NewtravelItem_alert_prompt": "提示",
  "OA_NewtravelItem_alert_cancel": "取消",
  "OA_NewtravelItem_alert_Confirm": "确认",
  "OA_NewtravelItem_alert_AddedSuccessfully": "添加成功",
  "OA_NewtravelItem_alert_network": "网络异常",
  "OA_NewtravelItem_list_flightandcar": "机票/车船票",
  "OA_NewtravelItem_list_airconstructionfee": "机场建设费",
  "OA_NewtravelItem_list_taxi": "出租车/市内车费",
  "OA_NewtravelItem_list_hotel": "宾馆",
  "OA_NewtravelItem_list_Hospitality": "招待费",
  "OA_NewtravelItem_list_correspondence": "通讯费",
  "OA_NewtravelItem_list_Conference": "会务费",
  "OA_NewtravelItem_list_Miscellaneous": "杂费",
  "OA_NewtravelItem_list_Gift": "礼品",
  "OA_NewtravelItem_list_others": "其他",
  "OA_NewtravelItem_list_formatofAmount": "您填写的金额格式不正确！",
  "OA_travelaccount_text_choose": "请选择",
  "OA_travelaccount_text_Limited": "限制最多800字",
  "OA_NewtravelAccount_alert_formatofinvoice": "发票张数必须是正整数！",
  "OA_NewtravelItem_open": "展开",
  "OA_NewtravelItem_close": "收起",


  "OA_authListCtrl_status_NotStarted": "未开始",
  "OA_authListCtrl_status_ongoing": "进行中",
  "OA_authListCtrl_status_completed": "已结束",
  "OA_authListCtrl_btn_Enabled": "已启用",
  "OA_authListCtrl_btn_Disabled": "未启用",
  "OA_authlist_text_authorization": "授权",
  "OA_authlist_alert_refreash": "下拉刷新…",
  "OA_authlist_text_startdate": "开始时间",
  "OA_authlist_text_enddate": "结束时间",
  "OA_authlist_alert_counts": "您近三个月没有授权记录哟~",
  "OA_authupdateAndAdd_text_startdate": "开始日期",
  "OA_authupdateAndAdd_text_choose": "请选择",
  "OA_authupdateAndAdd_text_enddate": "结束时间",
  "OA_authupdateAndAdd_text_agent": "代理人",
  "OA_authupdateAndAdd_text_delete": "删除",
  "OA_authupdateAndAdd_text_update": "更新",
  "OA_authupdateAndAdd_text_authorize": "授权",
  "OA_authupdateAndAdd_text_authorize_history": "代理授权历史",
  "OA_authupdateAndAdd_text_search": "姓名/首字母/拼音/域帐号",
  "OA_authUpdateAndAddCtrl_text_add": "新增授权",
  "OA_authUpdateAndAddCtrl_text_update": "修改授权",
  "OA_authUpdateAndAddCtrl_text_end": "结束授权",
  "OA_authUpdateAndAddCtrl_alert_prompt": "提示",
  "OA_authUpdateAndAddCtrl_alert_confirm": "确定",
  "OA_authUpdateAndAddCtrl_alert_enable": "启用",
  "OA_authUpdateAndAddCtrl_alert_updatefailed": "更新失败",
  "OA_authUpdateAndAddCtrl_alert_deletefailed": "删除失败",
  "OA_authUpdateAndAddCtrl_alert_warning": "警告",
  "OA_authUpdateAndAddCtrl_alert_confirmdelete": "确认删除该授权？",
  "OA_authUpdateAndAddCtrl_alert_confirmend": "确认结束该授权？",
  "OA_authUpdateAndAddCtrl_alert_cancel": "取消",
  "OA_authUpdateAndAddCtrl_alert_confirm": "确认",
  "OA_authUpdateAndAddCtrl_alert_selectstartdate": "请选择开始时间",
  "OA_authUpdateAndAddCtrl_alert_selectenddate": "请选择结束时间",
  "OA_authUpdateAndAddCtrl_alert_selectagent": "请选择代理人",
  "OA_authUpdateAndAddCtrl_alert_authorizefailed": "授权失败",
  "OA_authupdateAndAdd_text_choose": "请选择",


  "OA_addpointsapplydetail_text_formdetail": "表单详情",
  "OA_addpointsapplydetail_alert_refreash": "下拉刷新…",
  "OA_addpointsapplydetail_text_operator": "处理人",
  "OA_addpointsapplydetail_text_applynumber": "申请单号",
  "OA_addpointsapplydetail_text_applytime": "申请时间",
  "OA_addpointsapplydetail_text_applystatus": "申请状态",
  "OA_addpointsapplydetail_text_approving": "审",
  "OA_addpointsapplydetail_text_Expectedapprovers": "预计审批人",
  "OA_addpointsapplydetail_text_Costcenter": "费用中心",
  "OA_addpointsapplydetail_text_itemname": "项目名称",
  "OA_addpointsapplydetail_text_itemnumber": "项目编号",
  "OA_addpointsapplydetail_text_totalpoints": "总积分",
  "OA_addpointsapplydetail_text_amount": "总成本",
  "OA_addpointsapplydetail_text_remark": "备注",
  "OA_addpointsapplydetail_text_attachment": "附件",
  "OA_addpointsapplydetail_text_workflowlog": "流转日志",
  "OA_AddPointsApplyDetailCtrl_text_explanation": "可输入理由",
  "OA_AddPointsApplyDetailCtrl_text_approval comments": "请填写审批意见",
  "OA_AddPointsApplyDetailCtrl_text_approval explanationRequired": "可输入理由（必填）",
  "OA_AddPointsApplyDetailCtrl_text_refuse": "拒绝",
  "OA_AddPointsApplyDetailCtrl_text_ReasontoRefuse": "请填写拒绝理由",
  "OA_AddPointsApplyDetailCtrl_text_NoMoreForms": "您本次的审批已完成",

  "OA_businesscardprintingdetail_text_companyChinese": "公司(CN)",
  "OA_businesscardprintingdetail_text_companyEnglish": "公司(EN)",
  "OA_businesscardprintingdetail_text_nameChinese": "姓名(CN)",
  "OA_businesscardprintingdetail_text_nameEnglish": "姓名(EN)",
  "OA_businesscardprintingdetail_text_positionChinese": "职位(CN)",
  "OA_businesscardprintingdetail_text_positionEnglish": "职位(EN)",
  "OA_businesscardprintingdetail_text_departmentChinese": "部门(CN)",
  "OA_businesscardprintingdetail_text_departmentEnglish": "部门(EN)",
  "OA_businesscardprintingdetail_text_addressChinese": "地址(CN)",
  "OA_businesscardprintingdetail_text_addressEnglish": "地址(EN)",
  "OA_businesscardprintingdetail_text_officetelphone": "办公电话",
  "OA_businesscardprintingdetail_text_officefaxnumber": "传真电话",
  "OA_businesscardprintingdetail_text_mobilephone": "手机寻呼",
  "OA_businesscardprintingdetail_text_email": "电子邮件",
  "OA_businesscardprintingdetail_text_wechatID": "微信号",
  "OA_businesscardprintingdetail_text_numberofboxes": "申印盒数",

  "OA_chapterBusinessdetail_text_chapter_company": "用章公司",
  "OA_chapterBusinessdetail_text_chapter_department": "用章部门",
  "OA_chapterBusinessdetail_text_chapter_reason": "用章理由",
  "OA_ChapterInvestmentdetail_text_filetype": "文件类型",
  "OA_ChapterInvestmentdetail_text_reason": "事由",
  "OA_ChapterSealEngravingdetai_text_stamper_usefor": "印章用途",
  "OA_ChapterSealEngravingdetai_text_stamper_unit": "印章单位",
  "OA_ChapterSealEngravingdetai_text_stamper_content": "印章内容",
  "OA_ChapterSealEngravingdetai_text_remark": "备注",
  "OA_contractpaymentdetail_text_paymentpayee": "收款单位",
  "OA_contractpaymentdetail_text_contractnumber": "合同编号",
  "OA_contractpaymentdetail_text_totalcontractamount": "合同总价",
  "OA_contractpaymentdetail_text_unsure": "不定",
  "OA_contractpaymentdetail_text_amountpaid": "已付金额",
  "OA_contractpaymentdetail_text_amountpaidforthistime": "本次付款",
  "OA_contractpaymentdetail_text_amountpaidforthistimeRMB": "人民币",
  "OA_contractpaymentdetail_text_depositforthistime": "本次押金",
  "OA_contractpaymentdetail_text_depositforthistimeRMB": "人民币",
  "OA_contractpaymentdetail_text_depositoffsetforthistime": "本次抵充",
  "OA_contractpaymentdetail_text_depositoffsetforthistimeRMB": "人民币",
  "OA_contractpaymentdetail_text_paymentbalance": "欠款余额",
  "OA_contractpaymentdetail_text_paymentreason": "付款理由",
  "OA_contractpaymentdetail_text_allocationtime": "分摊时间",
  "OA_contractpaymentdetail_text_budgetproportion": "预算比例",
  "OA_contractpaymentdetail_text_multiplecostcenter": "多费用中心",
  "OA_costaccountdetail_text_expensetype": "费用种类",
  "OA_costaccountdetail_text_totalamount": "总额",
  "OA_costaccountdetail_text_dateofoccurance": "发生日期",
  "OA_costaccountcontroller_text_prompt": "请去PC端添加项目",

  "OA_costticketsapplydetail_text_tickettype": "游票类型",
  "OA_costticketsapplydetail_text_ticketform": "游票形式",
  "OA_costticketsapplydetail_text_ticketnumber": "项目编号",
  "OA_costticketsapplydetail_text_dateofeffect": "生效日期",
  "OA_costticketsapplydetail_text_ticketname": "项目名称",
  "OA_costticketsapplydetail_text_ticketnature": "项目性质",
  "OA_costticketsapplydetail_text_amount": "发放金额",
  "OA_costticketsapplydetail_text_expectedcost": "预计成本",
  "OA_costticketsapplydetail_text_expecteduserate": "预计使用",
  "OA_couponapplydetail_text_couponsnumber": "项目编号",
  
  "OA_delieverydetail_text_recipientaddress": "收件地址",
  "OA_delieverydetail_text_recipientname": "收件姓名",
  "OA_delieverydetail_text_recipientphone": "收件电话",
  "OA_delieverydetail_text_carrier": "承运商",
  "OA_delieverydetail_text_waybillnumber": "运单号",
  "OA_delieverydetail_text_expresstype": "快递类型",
  "OA_delieverydetail_text_expressdetail": "快递详情",
  "OA_devicepurchasedetail_text_model": "规格、型号",
  "OA_devicepurchasedetail_text_quantity": "数量",
  "OA_devicepurchasedetail_text_unitprice": "金额",
  "OA_devicepurchasedetail_text_totalprice": "总价",
  "OA_devicepurchasedetail_text_explanation": "说明/用途",
  "OA_devicepurchasedetail_text_auditdepartment": "审核部门",

  "OA_fixedassertallocationdetail_text_Affiliatedcompany": "所属公司",
  "OA_fixedassertallocationdetail_text_fromdepartment": "调出部门",
  "OA_fixedassertallocationdetail_text_todepartment": "调入部门",
  "OA_fixedassertallocationdetail_text_assettype": "资产类别",
  "OA_fixedassertallocationdetail_text_assetnumber": "资产编号",
  "OA_fixedassertallocationdetail_text_usedate": "使用日期",
  "OA_fixedassertallocationdetail_text_place": "地点",
  "OA_fixedassetsapplydetail_text_receiptdepartment": "领用部门",
  "OA_fixedassetsapplydetail_text_auditnumber": "评审编号",
  "OA_fixedassetsscrappeddetail_text_scrappeddepartment": "报废部门",
  "OA_fixedassetsscrappeddetail_text_residualvalue": "实际金额",

  "OA_formbutton_btn_countersign": "会签",
  "OA_formbutton_btn_approval": "审批",
  "OA_formbutton_btn_refuse": "拒绝",
  "OA_formbutton_btn_next": "下一单",

  "OA_giftcollardetail_text_customername": "客户名称",
  "OA_giftcollardetail_text_applyforuse": "申领用途",
  "OA_giftcollardetail_text_giftdetail": "礼品明细",
  "OA_giftcollardetail_text_giftname": "礼品名称",
  "OA_giftcollardetail_text_listofitems": "物品清单",

  "OA_incomecontractreviewdetail_text_contractingcompany": "签约公司",
  "OA_incomecontractreviewdetail_text_contractnumber": "合同编号",
  "OA_incomecontractreviewdetail_text_contractname": "合同名称",
  "OA_incomecontractreviewdetail_text_agreementunit": "协议单位",
  "OA_incomecontractreviewdetail_text_contractamount": "合同金额",
  "OA_incomecontractreviewdetail_text_contractdeposit": "押金",
  "OA_incomecontractreviewdetail_text_keyword": "关键字",
  "OA_incometicketsapplydetail_text_couponsissuingcompany": "开票公司",
  "OA_incometicketsapplydetail_text_couponsdiscountrate": "折扣率",
  "OA_incometicketsapplydetail_text_couponsactualreceipt": "实际收款",
  "OA_incometicketsapplydetail_text_limit": "合同有效期",

  "OA_letterdetail_text_letterdetai": "信件详情",
  "OA_letterdetail_text_letteritemdetai": "信件明细",
  "OA_letterdetail_text_totalquantity": "总数",
  "OA_letterdetail_text_lettertype": "信件类型",

  "OA_MICEgroupapplydetail_text_miceteamnumer": "团队号",
  "OA_MICEgroupapplydetail_text_miceteamamount": "团队金额",
  
  "OA_joinerctrl_alert_timeout": "网络请求超时！",
  "OA_joinerctrl_alert_chooseotherperson": "不能选择自己作为会签人",
  "OA_joinerctrl_alert_alreadychoosed": "已经选择此人",
  "OA_joinerctrl_alert_choosesomeone": "请选择会签人",
  "OA_joiner_text_add": "添加会签人",
  "OA_joiner_text_name": "添加历史",
  "OA_joiner_text_addhistory": "已添加列表",
  "OA_joiner_text_addedlist": "请填写添加会签人的理由",
  "OA_joiner_text_select": "(选填)",
  "OA_joiner_text_add_prompt": "添加会签人不能为空",

  "OA_officesuppliescollardetail_text_itemname": "物品名称",
  "OA_officesuppliescollardetail_text_officesuppliesdetail": "办公用品明细",

  "OA_pointspolicyapply_text_integralname": "政策名称",
  "OA_pointspolicyapply_text_integraltype": "政策类型",
  "OA_pointspolicyapply_text_releasedintegral": "发放积分",
  "OA_pointspolicyapply_text_expectedintegral": "预发积分",
  "OA_pointspolicyapply_text_integralrule": "发放规则",

  "OA_purchasecontractreview_text_vendor": "供应商",
  "OA_sendcardetail_text_usecarreason": "用车原因",
  "OA_sendcardetail_text_usecardetail": "派车明细",
  "OA_sendcardetail_text_usecardate": "用车时间",
  "OA_sendcardetail_text_usecarorigin": "始发地",
  "OA_sendcardetail_text_usecardestination": "目的地",
  "OA_staffloandetail_text_applyamount": "申请金额",

  "OA_feereport_text_feepeport": "费用统计",
  "OA_feereportCtrl_text_used": "已使用",
  "OA_feereportCtrl_text_unused": "未使用",
  "OA_feereportCtrl_text_costrate": "费用占比",
  "OA_feereportCtrl_text_withoutbudget": "无预算",
  "OA_feereportCtrl_text_Errorofbudget": "获取费用中心预算异常",
  "OA_feereportCtrl_budgettop10": "预算Top10",
  "OA_feereportCtrl_text_Errorofallbudget": "获取费用中心各类型预算异常",
  "OA_feereportCtrl_personalfeetop10": "个人费用Top10",
  "OA_feereportCtrl_text_Erroroffee": "获取费用中心费用异常",
  "OA_feereportCtrl_text_Q1costrate": "Q1费用占比",
  "OA_feereportCtrl_text_userate": "使用率",
  "OA_feereportCtrl_text_totalbudget": "总预算: ",
  "OA_feereportCtrl_text_usedrate": "已使用率：",
  "OA_feereportCtrl_text_year": "年",
  "OA_feereportCtrl_text_month": "月",

  "OA_applyapproval_text_countersign": "加入会签",
  "OA_applyapproval_text_searchcountersign": "搜索会签人",
  "OA_formdetail_text_viewexpectedapprovers": "查看预计审批人",
  
  "eform_warning": "通知",
  "eform_network": "网络异常",
  "eform_title": "待审批",
  "eform_index_tab_all": "全部",
  "eform_index_tab_ehr": "人事",
  "eform_index_refresher": "下拉刷新",
  "eform_index_order_time": "时间排序",
  "eform_index_order_user": "申请人排序",
  "eform_index_order_subject": "主题排序",
  "eform_index_span_sign": "代签",
  "eform_index_span_joinsign": "会签中",
  "eform_index_noapp_tip": "当前没有您的审批单哟",
  "eform_index_nooa_tip": "OA审批单暂不支持，敬请期待",
  "eform_index_click_goauth": "审批授权",
  "eform_index_click_goauthlist": "我的已授权",
  "eform_index_toggle_showjoinapp": "显示会签中的单据",
  "eform_index_OAgetAgentList_tipinfo": "OA授权列表获取失败，请稍后重试",
  "eform_index_OAupdateAgent_tipinfo": "OA授权收回失败，请稍后重试",
  "eform_index_EhrgetAgentList_tipinfo": "Ehr授权列表获取失败，请稍后重试",
  "eform_index_EhrupdateAgent_tipinfo": "Ehr授权收回失败，请稍后重试",
  "eform_index_ITAgent_tipinfo": "IT收回授权失败，请稍后重试",
  "eform_index_AllAgent_tipinfo": "您的权限已全部收回",

  "eform_it_span_process": "审批流程",
  "eform_it_checkbox_all": "全选",
  "eform_it_checkbox_selected": "已选",
  "eform_it_checkbox_item": "项",
  "eform_it_btn_joindecline": "会签拒绝",
  "eform_it_btn_joinapprove": "会签通过",
  "eform_it_btn_next": "下一单",
  "eform_it_btn_signer": "会签人",
  "eform_it_btn_decline": "拒绝",
  "eform_it_btn_approve": "通过",
  "eform_it_status_pending": "待审批",
  "eform_it_status_approve": "审批通过",
  "eform_it_status_decline": "审批驳回",
  "eform_it_status_cancel1": "本级节点已取消",
  "eform_it_status_cancel2": "上级节点已取消",
  "eform_it_warn_noselect": "您还没有选择任何单据",
  "eform_it_warn_noreason": "请输入理由！",
  "eform_it_warn_goctripteam": "获取跳转信息失败，请稍后重试！",
  "eform_itjoin_title": "添加会签人",
  "eform_itjoin_search_name": "姓名",
  "eform_itjoin_search_initials": "首字母",
  "eform_itjoin_search_pinyin": "拼音",
  "eform_itjoin_search_ad": "域帐号",
  "eform_itjoin_search_cancel": "取消",
  "eform_itjoin_signer_history": "添加历史",
  "eform_itjoin_signer_list": "已添加列表",
  "eform_itjoin_signer_reason": "请填写添加会签人的理由",
  "eform_itjoin_reason_placeholder": "选填",
  "eform_itjoin_btn_cancel": "取消",
  "eform_itjoin_btn_ok": "确认",
  "eform_itjoin_warn_self": "不能选择自己作为会签人",
  "eform_itjoin_warn_selected": "已经选择此人",
  "eform_itjoin_warn_nosigner": "请选择会签人",

  "eform_ehr_span_leavedate": "请假日期",
  "eform_ehr_span_datehours": "每天时段",
  "eform_ehr_span_leavedaynum": "请假小时数",
  "eform_ehr_span_day": "天",
  "eform_ehr_span_hours": "小时",
  "eform_ehr_span_tips": "说明",
  "eform_ehr_batchApplyTitle": "请假申请单",
  "eform_ehr_noAduiterList": "当前单据审批流为空!",
  "eform_ehr_status_0": "待审批",
  "eform_ehr_status_1": "已审批",
  "eform_ehr_status_3": "会签中",
  "eform_ehr_status_4": "退回申请人",
  "eform_ehr_status_5": "退回上一级审批人",
  "eform_ehr_AuditerStatus_3": "该单据在会签中,您暂时无法进行审批。",
  "eform_ehr_sign_comment": "请填写会签意见(选填)",
  "eform_ehr_sign_reason": "请填写拒绝理由(必填)",

  "eform_remedy_span_Apprvoers": "审批人",
  "eform_remedy_span_Summary": "概要",
  "eform_remedy_span_Detail": "描述",

  "eform_AccreditList_view_title": "我的已授权",
  "eform_AccreditList_tabs_all": "全部",
  "eform_AccreditList_tabs_remedy": "流程",
  "eform_AccreditList_refresher_pullingText": "下拉刷新...",
  "eform_AccreditList_div_noApproving": "当前没有您的授权单哟~",
  "eform_AccreditList_div_timeUntil": "至",
  "eform_AccreditList_div_deadline": "截止日期",
  "eform_AccreditList_checkbox_all": "全选",
  "eform_AccreditList_button_takeBack": "收回",
  "eform_AccreditListCtrl_item_status": "授权中",
  "eform_AccreditListCtrl_jsListStatus_authIn": "授权中",
  "eform_AccreditListCtrl_jsListStatus_unBegin": "未开始",
  "eform_AccreditListCtrl_jsrole_all": "所有权限",
  "eform_AccreditListCtrl_jsOnDelete_template": "您将会收回该授权",
  "eform_AccreditListCtrl_jsOnDelete_title": "温馨提示",
  "eform_AccreditListCtrl_jsOnDelete_buttonOK": "确认收回",
  "eform_AccreditListCtrl_jsOnDelete_buttonCancel": "我再想想",
  "eform_AccreditListCtrl_jsOAgetAgentList_callbackError": "OA授权列表获取失败，请稍后重试",
  "eform_AccreditListCtrl_jsGetAuthList_callbackError": "Ehr授权列表获取失败，请稍后重试",
  "eform_AccreditListCtrl_jsAuditAuthorizeQuery_callbackError": "IT授权列表获取失败，请稍后重试",
  "eform_AccreditListCtrl_jsQueryalternate_statusError": "流程授权列表获取失败，请稍后重试",
  "eform_AccreditListCtrl_jsSelectAll_selectNone": "您没有选中对象哟~",
  "eform_AccreditListCtrl_jsOAupdateAgent_callbackError": "OA授权收回失败，请稍后重试",
  "eform_AccreditListCtrl_jsCancelAuth_callbackError": "Ehr授权收回失败，请稍后重试",
  "eform_AccreditListCtrl_jsAuditAuthorizeDelete_callbackError": "IT收回授权失败，请稍后重试",
  "eform_AccreditListCtrl_jsRemedyCancel_callbackError": "Remedy收回授权失败，请稍后重试",
  "eform_AccreditListCtrl_jsWaitDelete_deleteSuccess": "授权收回成功",

  "eform_updateAccredit_view_title": "审批授权",
  "eform_updateAccredit_button_submit": "提交",
  "eform_updateAccredit_inputLable_startDate": "开始日期",
  "eform_updateAccredit_p_select": "请选择",
  "eform_updateAccredit_inputLable_endDate": "结束日期",
  "eform_updateAccredit_inputLable_Agent": "代理人",
  "eform_updateAccredit_input_placeholder": "姓名/首字母/拼音/域帐号",
  "eform_updateAccredit_span_searchHistory": "搜索历史",
  "eform_updateAccredit_label_clearSearchHistory": "清空搜索历史",
  "eform_updateAccredit_div_tip": "*以下方填写的代理人为准，可不填",

  "eform_accreditCtrl_jsmonthList_Jan": "一月",
  "eform_accreditCtrl_jsmonthList_Feb": "二月",
  "eform_accreditCtrl_jsmonthList_Mar": "三月",
  "eform_accreditCtrl_jsmonthList_Apr": "四月",
  "eform_accreditCtrl_jsmonthList_May": "五月",
  "eform_accreditCtrl_jsmonthList_June": "六月",
  "eform_accreditCtrl_jsmonthList_July": "七月",
  "eform_accreditCtrl_jsmonthList_Aug": "八月",
  "eform_accreditCtrl_jsmonthList_Sep": "九月",
  "eform_accreditCtrl_jsmonthList_Oct": "十月",
  "eform_accreditCtrl_jsmonthList_Nov": "十一月",
  "eform_accreditCtrl_jsmonthList_Dec": "十二月",
  "eform_accreditCtrl_jsweeklist_Sun": "日",
  "eform_accreditCtrl_jsweeklist_Mon": "一",
  "eform_accreditCtrl_jsweeklist_Tues": "二",
  "eform_accreditCtrl_jsweeklist_Wed": "三",
  "eform_accreditCtrl_jsweeklist_Thur": "四",
  "eform_accreditCtrl_jsweeklist_Fri": "五",
  "eform_accreditCtrl_jsweeklist_Sat": "六",
  "eform_accreditCtrl_jsdatePopup_todayLabel": "今天",
  "eform_accreditCtrl_jsdatePopup_closeLabel": "取消",
  "eform_accreditCtrl_jsdatePopup_setLabel": "确定",
  "eform_accreditCtrl_jsAlert_warnTitle": "警告",
  "eform_accreditCtrl_jsAlert_warnInfo": "开始时间必须小于结束时间！",
  "eform_accreditCtrl_jsAlert_startPopup": "开始日期",
  "eform_accreditCtrl_jsAlert_endPopup": "结束日期",
  "eform_accreditCtrl_jsScope_httpAlert": "网络请求超时!",
  "eform_accreditCtrl_jsPopup_title": "提示",
  "eform_accreditCtrl_jsTipInfo_noRole": "您没有角色可以授权",
  "eform_accreditCtrl_jsTipInfo_busyNetwork": "网络忙，请稍后",
  "eform_accreditCtrl_jsTipInfo_ehrError": "EHR授权失败，请稍后重试",
  "eform_accreditCtrl_jsTipInfo_itError": "IT授权失败，请稍后重试，谢谢",
  "eform_accreditCtrl_jsTipInfo_oaError": "OA授权失败，请稍后重试",
  "eform_accreditCtrl_jsTipInfo_openLicense": "您没有开启授权",
  "eform_accreditCtrl_jsTipInfo_noDate": "请选择日期",
  "eform_accreditCtrl_jsTipInfo_noOaAgent": "请填写OA代理人",
  "eform_accreditCtrl_jsTipInfo_noITAgent": "请填写IT代理人",
  "eform_accreditCtrl_jsTipInfo_noEhrAgent": "请填写EHR代理人",
  "eform_accreditCtrl_jsTipInfo_noRemedyAgent": "请填写流程代理人",
  "eform_accreditCtrl_jsTipInfo_approveSuccess": "授权成功",

  "ehr_quit_title": "待审批",
  "ehr_quit_btn_refresh": "下拉刷新",
  "ehr_quit_p_docutype": "离职申请交接单",
  "ehr_quit_p_basicinfo": "基本信息",
  "ehr_quit_p_approvalinfo": "审批信息",
  "ehr_quit_p_process": "审批流程",
  "ehr_quit_p_applicant": "离职人员",
  "ehr_quit_p_applyDate": "申请时间",
  "ehr_quit_p_department": "部门",
  "ehr_quit_p_hireValid": "入职日期",
  "ehr_quit_p_EmpLevel": "职级",
  "ehr_quit_p_ProbationEndDate": "试用期结束日",
  "ehr_quit_p_ContractEndDate": "合同结束日",
  "ehr_quit_p_QuitType": "辞退类型",
  "ehr_quit_p_PulishID": "处分关联单据号",
  "ehr_quit_p_EmpAttribute": "员工属性",
  "ehr_quit_p_ContractLimit": "合同期限",
  "ehr_quit_p_QuitStyle": "离职类型",
  "ehr_quit_p_QuitReason": "离职原因",
  "ehr_quit_p_IsMakeUp": "是否补偿",
  "ehr_quit_p_AvgSalary": "平均月薪",
  "ehr_quit_p_AgeReference": "年限参考",
  "ehr_quit_p_Compensation": "补偿金额",
  "ehr_quit_p_MakeUpType": "补偿类型",
  "ehr_quit_p_MakeUpProcess": "补偿计算过程",
  "ehr_quit_p_QuitRemark": "备注",
  "ehr_quit_p_EmpType": "员工分类",
  "ehr_quit_p_Injury": "工伤信息提示",
  "ehr_quit_p_ItemList": "物品交接清单",
  "ehr_quit_btn_Pass": "通过",
  "ehr_quit_btn_AddCounter": "会签人",
  "ehr_quit_btn_Refuse": "拒绝",
  "ehr_quit_btn_ReApplicant": "退回申请人",
  "ehr_quit_btn_ReApproval": "退回上一级",
  "ehr_quit_label_IsCompetition": "请选择竞业限制是否履行",
  "ehr_quit_label_QuitCode": "离职代码",
  "ehr_quit_label_QuitReaonRemark": "离职原因备注",
  "ehr_quit_label_HRNotes": "HR备注",
  "ehr_quit_label_AccCloseDate": "帐号关闭日期",
  "ehr_quit_label_TerminationMonth": "离职归入月",
  "ehr_quit_label_IsCardReturn": "门禁卡",
  "ehr_quit_label_IsHandBook": "员工手册",
  "ehr_quit_label_select": "请选择",
  "ehr_quit_jsalert_warn": "通知",
  "ehr_quit_jsalert_Network": "网络异常",
  "ehr_quit_jsalert_noAduiterList": "当前单据审批流为空",
  "ehr_quit_jstext_Status0": "待审批",
  "ehr_quit_jstext_Status1": "已审批",
  "ehr_quit_jstext_Status3": "会签中",
  "ehr_quit_jstext_Status4": "退回申请人",
  "ehr_quit_jstext_Status5": "退回上一级审批人",
  "ehr_quit_jsalert_min": "你选择的日期不得早于",
  "ehr_quit_jsalert_max": "你选择的日期必须早于",
  "ehr_quit_jsdate_Jan": "一月",
  "ehr_quit_jsdate_Feb": "二月",
  "ehr_quit_jsdate_Mar": "三月",
  "ehr_quit_jsdate_Apr": "四月",
  "ehr_quit_jsdate_May": "五月",
  "ehr_quit_jsdate_June": "六月",
  "ehr_quit_jsdate_July": "七月",
  "ehr_quit_jsdate_Aug": "八月",
  "ehr_quit_jsdate_Sep": "九月",
  "ehr_quit_jsdate_Oct": "十月",
  "ehr_quit_jsdate_Nov": "十一月",
  "ehr_quit_jsdate_Dec": "十二月",
  "ehr_quit_jsdate_Sun": "日",
  "ehr_quit_jsdate_Mon": "一",
  "ehr_quit_jsdate_Tues": "二",
  "ehr_quit_jsdate_Wed": "三",
  "ehr_quit_jsdate_Thur": "四",
  "ehr_quit_jsdate_Fri": "五",
  "ehr_quit_jsdate_Sat": "六",
  "ehr_quit_jsdate_selectDate": "选择日期",
  "ehr_quit_jsdate_todayLabel": "今天",
  "ehr_quit_jsalert_cancel": "取消",
  "ehr_quit_jsalert_confirm": "确定",
  "ehr_quit_jsalert_IsCompetition": "请选择竞业限制是否履行",
  "ehr_quit_jsalert_QuitCode": "请选择离职代码",
  "ehr_quit_jsalert_QuitReaonRemark": "请填写离职原因备注",
  "ehr_quit_jsalert_HRNotes": "请填写HR备注",
  "ehr_quit_jsalert_AccCloseDate": "请选择帐号关闭日期",
  "ehr_quit_jsalert_TerminationMonth": "请选择离职归入月",
  "ehr_quit_jsalert_success": "成功",
  "ehr_quit_jsalert_comment": "请填写会签意见",
  "ehr_quit_jsalert_ispass": "确认通过?",
  "ehr_quit_jsalert_isRefuse": "确认拒绝?",
  "ehr_quit_jsalert_reason": "请填写拒绝理由",
  "ehr_quit_label_SJLZRQ": "实际离职日期",
  "ehr_quit_label_QXZSJLZRQ": "请选择实际离职日期",
  "ehr_quit_label_QYWHSC": "企业文化手册",
  "ehr_quit_p_BZ": "币种",

  "ehr_addCountersign_title": "添加会签人",
  "ehr_addCountersign_search_name": "姓名",
  "ehr_addCountersign_search_initials": "首字母",
  "ehr_addCountersign_search_pinyin": "拼音",
  "ehr_addCountersign_search_ad": "域帐号",
  "ehr_addCountersign_search_cancel": "取消",
  "ehr_addCountersign_signer_history": "添加历史",
  "ehr_addCountersign_signer_list": "已添加列表",
  "ehr_addCountersign_signer_reason": "请填写添加会签人的理由",
  "ehr_addCountersign_reason_placeholder": "(选填)",
  "ehr_addCountersign_btn_cancel": "取消",
  "ehr_addCountersign_btn_ok": "确认",
  "ehr_addCountersign_warn_self": "不能选择自己作为会签人",
  "ehr_addCountersign_warn_selected": "已经选择此人",
  "ehr_addCountersign_warn_nosigner": "请选择会签人",
  "ehr_addCountersign_warn_warning": "通知",
  "ehr_addCountersign_warn_network": "网络异常",
  "ehr_addCountersign_jsalert_success": "成功",

  "ehr_transferApplication_title": "待审批",
  "ehr_transferApplication_btn_refresh": "下拉刷新",
  "ehr_transferApplication_p_docutype": "人员调动单",
  "ehr_transferApplication_p_basicinfo": "基本信息",
  "ehr_transferApplication_p_process": "审批流程",
  "ehr_transferApplication_p_applicant": "申请人",
  "ehr_transferApplication_p_applyDate": "申请时间",
  "ehr_transferApplication_p_TransferEmp": "调动人员",
  "ehr_transferApplication_p_EmpType": "员工分类 ",
  "ehr_transferApplication_p_OperateType": "操作类型",
  "ehr_transferApplication_p_MoveDate": "调动日期",
  "ehr_transferApplication_p_Department": "调出部门/岗位",
  "ehr_transferApplication_p_TransferDepart": "调入部门/岗位",
  "ehr_transferApplication_p_EmpLevel": "职级变动",
  "ehr_transferApplication_p_PerformanceB": "绩效变动",
  "ehr_transferApplication_p_WorkLocationB": "当前实际工作地",
  "ehr_transferApplication_p_WorkLocationA": "调动后实际工作地",
  "ehr_transferApplication_p_MoveReason": "调动原因",
  "ehr_transferApplication_p_ExtraRule": "附加约定",
  "ehr_transferApplication_p_BaseSalary": "调动后基本工资",
  "ehr_transferApplication_p_WealthSalary": "调动后财富工资",
  "ehr_transferApplication_p_TechSalary": "调动后技能工资",
  "ehr_transferApplication_p_PlaceSubsidy": "异地津贴",
  "ehr_transferApplication_p_MoveSubsidy": "搬家补贴",
  "ehr_transferApplication_p_HouseSubsidy": "住房报销",
  "ehr_transferApplication_p_GiveOutEndDate": "拟发放结束日",
  "ehr_transferApplication_btn_Pass": "通过",
  "ehr_transferApplication_btn_AddCounter": "会签人",
  "ehr_transferApplication_btn_Refuse": "拒绝",
  "ehr_transferApplication_btn_ReApplicant": "退回申请人",
  "ehr_transferApplication_btn_ReApproval": "退回上一级",
  "ehr_transferApplication_label_IsCompetition": "请选择竞业限制是否履行",
  "ehr_transferApplication_label_select": "请选择",
  "ehr_transferApplication_jsalert_warn": "通知",
  "ehr_transferApplication_jsalert_Network": "网络异常",
  "ehr_transferApplication_jsalert_noAduiterList": "当前单据审批流为空",
  "ehr_transferApplication_jstext_Status0": "待审批",
  "ehr_transferApplication_jstext_Status1": "已审批",
  "ehr_transferApplication_jstext_Status3": "会签中",
  "ehr_transferApplication_jstext_Status4": "退回申请人",
  "ehr_transferApplication_jstext_Status5": "退回上一级审批人",
  "ehr_transferApplication_jsalert_success": "成功",
  "ehr_transferApplication_jsalert_comment": "请填写会签意见",
  "ehr_transferApplication_jsalert_ispass": "确认通过?",
  "ehr_transferApplication_jsalert_isRefuse": "确认拒绝?",
  "ehr_transferApplication_jsalert_reason": "请填写拒绝理由",
  "ehr_transferApplication_p_DQCBD": "当前参保地",
  "ehr_transferApplication_p_DDHCBD": "调动后参保地",
  "ehr_transferApplication_p_BZ": "币种",
  "ehr_transferApplication_p_JYXZYW": "竞业限制义务",
  "ehr_transferApplication_p_DRZX": "调入小组",

  "ehr_ContractCtrl_title": "待审批",
  "ehr_ContractCtrl_p_docutype": "合同到期续签意见表",
  "ehr_ContractCtrl_btn_refresh": "下拉刷新",
  "ehr_ContractCtrl_p_basicinfo": "基本信息",
  "ehr_ContractCtrl_p_approvalinfo": "审批信息",
  "ehr_ContractCtrl_p_process": "审批流程",
  "ehr_ContractCtrl_p_xqry": "续签人员",
  "ehr_ContractCtrl_p_sqsj": "申请时间",
  "ehr_ContractCtrl_p_bm": "部门",
  "ehr_ContractCtrl_p_rzrq": "入职日期",
  "ehr_ContractCtrl_p_zj": "职级",
  "ehr_ContractCtrl_p_htjsr": "合同结束日",
  "ehr_ContractCtrl_p_lshtxx": "历史合同信息",
  "ehr_ContractCtrl_p_qdcs": "08年后签订次数",
  "ehr_ContractCtrl_p_ts": "可续签年限的提示",
  "ehr_ContractCtrl_p_cfxx": "处分信息",
  "ehr_ContractCtrl_p_jkzt": "健康状态",
  "ehr_ContractCtrl_p_ygfl": "员工分类",
  "ehr_ContractCtrl_p_gsxx": "工伤信息",
  "ehr_ContractCtrl_p_zysx": "注意事项",
  "ehr_ContractCtrl_label_htlx": "拟续约合同类型",
  "ehr_ContractCtrl_label_sfxq": "是否续签",
  "ehr_ContractCtrl_label_xqnx": "续签年限",
  "ehr_ContractCtrl_label_jyxzqd": "竞业限制签订",
  "ehr_ContractCtrl_label_htgs": "合同公司",
  "ehr_ContractCtrl_label_xqgw": "续签岗位",
  "ehr_ContractCtrl_label_xqgslx": "续签工时类型",
  "ehr_ContractCtrl_label_xqhtzzr": "续签合同终止日",
  "ehr_ContractCtrl_label_xqhdsl": "续签后的司龄",
  "ehr_ContractCtrl_label_bz": "备注",
  "ehr_ContractCtrl_btn_tg": "通过",
  "ehr_ContractCtrl_btn_hqr": "会签人",
  "ehr_ContractCtrl_btn_jj": "拒绝",
  "ehr_ContractCtrl_btn_thsqr": "退回申请人",
  "ehr_ContractCtrl_btn_thsyj": "退回上一级",
  "ehr_ContractCtrl_btn_qx": "取消",
  "ehr_ContractCtrl_p_xzhtgs": "选择合同公司",
  "ehr_ContractCtrl_p_xzxqgw": "选择续签岗位",
  "ehr_ContractCtrl_jsalert_warn": "通知",
  "ehr_ContractCtrl_jsalert_Network": "网络异常",
  "ehr_ContractCtrl_jsalert_noAduiterList": "当前单据审批流为空",
  "ehr_ContractCtrl_jstext_Status0": "待审批",
  "ehr_ContractCtrl_jstext_Status1": "已审批",
  "ehr_ContractCtrl_jstext_Status3": "会签中",
  "ehr_ContractCtrl_jstext_Status4": "退回申请人",
  "ehr_ContractCtrl_jstext_Status5": "退回上一级审批人",
  "ehr_ContractCtrl_jsalert_confirm": "确定",
  "ehr_ContractCtrl_jsalert_success": "成功",
  "ehr_ContractCtrl_jsalert_ispass": "确认通过?",
  "ehr_ContractCtrl_jsalert_isRefuse": "确认拒绝?",
  "ehr_ContractCtrl_jsalert_comment": "请填写会签意见",
  "ehr_ContractCtrl_jsalert_reason": "请填写拒绝理由",
  "ehr_ContractCtrl_jsdate_Jan": "一月",
  "ehr_ContractCtrl_jsdate_Feb": "二月",
  "ehr_ContractCtrl_jsdate_Mar": "三月",
  "ehr_ContractCtrl_jsdate_Apr": "四月",
  "ehr_ContractCtrl_jsdate_May": "五月",
  "ehr_ContractCtrl_jsdate_June": "六月",
  "ehr_ContractCtrl_jsdate_July": "七月",
  "ehr_ContractCtrl_jsdate_Aug": "八月",
  "ehr_ContractCtrl_jsdate_Sep": "九月",
  "ehr_ContractCtrl_jsdate_Oct": "十月",
  "ehr_ContractCtrl_jsdate_Nov": "十一月",
  "ehr_ContractCtrl_jsdate_Dec": "十二月",
  "ehr_ContractCtrl_jsdate_Sun": "日",
  "ehr_ContractCtrl_jsdate_Mon": "一",
  "ehr_ContractCtrl_jsdate_Tues": "二",
  "ehr_ContractCtrl_jsdate_Wed": "三",
  "ehr_ContractCtrl_jsdate_Thur": "四",
  "ehr_ContractCtrl_jsdate_Fri": "五",
  "ehr_ContractCtrl_jsdate_Sat": "六",
  "ehr_ContractCtrl_jsdate_selectDate": "选择日期",
  "ehr_ContractCtrl_jsdate_todayLabel": "今天",
  "ehr_ContractCtrl_jsalert_NXYHTLX": "请选择拟续约合同类型",
  "ehr_ContractCtrl_jsalert_SFXQ": "请选择是否续签",
  "ehr_ContractCtrl_jsalert_XQNX": "请选择续签年限",
  "ehr_ContractCtrl_jsalert_JYXZQD": "请选择竞业限制签订",
  "ehr_ContractCtrl_jsalert_XQGW": "请选择续签岗位",
  "ehr_ContractCtrl_jsalert_HTGS": "请选择合同公司",
  "ehr_ContractCtrl_jsalert_XQGSLX": "请选择续签工时类型",
  "ehr_ContractCtrl_jsalert_XQHTZZR": "请选择续签合同终止日",
  "ehr_ContractCtrl_jsalert_BZ": "请填写备注",
  "ehr_ContractCtrl_label_select": "请选择",
  "ehr_ContractCtrl_label_number": "编号",
  "ehr_ContractCtrl_label_name": "名称",

  "ehr_punish_title": "待审批",
  "ehr_punish_p_CFYGSQS": "处分员工申请书",
  "ehr_punish_btn_refresh": "下拉刷新",
  "ehr_punish_p_basicinfo": "基本信息",
  "ehr_punish_p_process": "审批流程",
  "ehr_punish_p_CFYG": "处分员工",
  "ehr_punish_p_SQSJ": "申请时间",
  "ehr_punish_p_BM": "部门",
  "ehr_punish_p_ZJ": "职级",
  "ehr_punish_p_SQCFDJ": "申请处分等级",
  "ehr_punish_p_ZGLD": "主管领导",
  "ehr_punish_p_CFSY": "处分事由",
  "ehr_punish_p_CFYJ": "处分依据",
  "ehr_punish_p_CFYJIAN": "处分意见",
  "ehr_punish_p_CFGZSH": "处分告知书号",
  "ehr_punish_btn_SC": "生成",
  "ehr_punish_btn_Pass": "通过",
  "ehr_punish_btn_AddCounter": "会签人",
  "ehr_punish_btn_Refuse": "拒绝",
  "ehr_punish_btn_ReApplicant": "退回申请人",
  "ehr_punish_btn_ReApproval": "退回上一级",
  "ehr_punish_jsalert_warn": "通知",
  "ehr_punish_jsalert_Network": "网络异常",
  "ehr_punish_jsalert_noAduiterList": "当前单据审批流为空",
  "ehr_punish_jstext_Status0": "待审批",
  "ehr_punish_jstext_Status1": "已审批",
  "ehr_punish_jstext_Status3": "会签中",
  "ehr_punish_jstext_Status4": "退回申请人",
  "ehr_punish_jstext_Status5": "退回上一级审批人",
  "ehr_punish_jsalert_ispass": "确认通过?",
  "ehr_punish_jsalert_cancel": "取消",
  "ehr_punish_jsalert_confirm": "确认",
  "ehr_punish_jsalert_success": "成功",
  "ehr_punish_jsalert_comment": "请填写会签意见",
  "ehr_punish_jsalert_isRefuse": "确认拒绝?",
  "ehr_punish_jsalert_reason": "请填写拒绝理由",
  "ehr_punishCancel_p_CXCFSQS": "处分撤销申请书",
  "ehr_punishCancel_p_CXYJ": "撤销依据",

  "ehr_AdjustmentApplication_title": "待审批",
  "ehr_AdjustmentApplication_btn_refresh": "下拉刷新",
  "ehr_AdjustmentApplication_p_docutype": "薪资职级变动单",
  "ehr_AdjustmentApplication_p_basicinfo": "基本信息",
  "ehr_AdjustmentApplication_p_process": "审批流程",
  "ehr_AdjustmentApplication_p_AdjustmentEmp": "变动人员",
  "ehr_AdjustmentApplication_p_MoveDate": "变动日期",
  "ehr_AdjustmentApplication_p_Department": "所在部门/岗位",
  "ehr_AdjustmentApplication_p_EmpLevel": "职级变动",
  "ehr_AdjustmentApplication_p_PerformanceB": "绩效变动",
  "ehr_AdjustmentApplication_p_applicant": "申请人",
  "ehr_AdjustmentApplication_p_applyDate": "申请时间",
  "ehr_AdjustmentApplication_p_BaseSalary": "变动后基本工资",
  "ehr_AdjustmentApplication_p_WealthSalary": "变动后财富工资",
  "ehr_AdjustmentApplication_p_TechSalary": "变动后技能工资",
  "ehr_AdjustmentApplication_p_IncompetentPost": "是否为不胜任变动",
  "ehr_AdjustmentApplication_p_Remark": "备注",
  "ehr_AdjustmentApplication_p_BZ": "币种",

  "ehr_seal_p_docutype": "人事专用章",
  "ehr_seal_p_sealcompany": "用章公司",
  "ehr_seal_p_sealfiletype": "用章文件",
  "ehr_seal_p_sealuse": "用章用途",
  "ehr_seal_p_remak": "备注",
  "ehr_seal_p_warning": "注意事项",
  
  "ehr_overtime_title": "加班申请单",
  "ehr_overtime_span_1": "加班日期",
  "ehr_overtime_span_2": "加班时段",
  "ehr_overtime_span_3": "加班小时数",
  "ehr_overtime_span_4": "说明",
  "ehr_overtime_span_5": "考勤信息",
  "ehr_overtime_span_6": "已申请加班合计",
  "ehr_overtime_span_7": "小时",
  "ehr_overtime_span_8": "无打卡信息",
  "ehr_regular_title": "待审批",
  "ehr_regular_p_docutype": "试用人员评估考核表",
  "ehr_regular_p_regularUser": "转正人员",
  "ehr_regular_span_1": "是否转正",
  "ehr_regular_span_2": "转正人员自评",
  "ehr_regular_span_3": "业务知识",
  "ehr_regular_span_4": "a.相关工作知识及业务能力",
  "ehr_regular_span_5": "b.领悟并接受新知识能力",
  "ehr_regular_span_6": "工作态度",
  "ehr_regular_span_7": "a.对待工作的积极性和进取心",
  "ehr_regular_span_8": "b.能否承受额外的工作压力",
  "ehr_regular_span_9": "工作能力",
  "ehr_regular_span_10": "a.能否控制工作节奏",
  "ehr_regular_span_11": "b.领悟并完成指派的工作",
  "ehr_regular_span_12": "工作业绩",
  "ehr_regular_span_13": "a.对期限完毕工作的执行情况",
  "ehr_regular_span_14": "b.能否胜任并创造性完成工作",
  "ehr_regular_span_15": "团队精神",
  "ehr_regular_span_16": "a.对公司的认同程度",
  "ehr_regular_span_17": "b.能否受他人信任及相互激励",
  "ehr_regular_span_18": "c.是否与同事及领导和睦相处",
  "ehr_regular_span_19": "d.对部门的向心力及责任感",
  "ehr_regular_span_20": "评估意见",
  "ehr_regular_span_21": "员工转正信息(技能工资只适用于预订部'S'序列员工)",
  "ehr_regular_span_22": "当前基本工资",
  "ehr_regular_span_23": "当前技能工资",
  "ehr_regular_span_24": "约定转正基本工资",
  "ehr_regular_span_25": "入职转正约定",
  "ehr_regular_span_26": "主管填写",
  "ehr_regular_span_27": "转正基本工资",
  "ehr_regular_span_28": "转正技能工资",
  "ehr_regular_span_29": "工资货币",
  "ehr_regular_span_30": "转正职级",
  "ehr_regular_span_31": "部门人事填写",
  "ehr_regular_span_32": "转正日期",
  "ehr_regular_span_33": "期权发放形式",
  "ehr_regular_span_34": "绩效",
  "ehr_regular_alert_0": "是否转正不能为空",
  "ehr_regular_alert_1": "请填写转正人员自评",
  "ehr_regular_alert_2": "请选择业务知识a",
  "ehr_regular_alert_3": "请选择业务知识b",
  "ehr_regular_alert_4": "请选择工作态度a",
  "ehr_regular_alert_5": "请选择工作态度b",
  "ehr_regular_alert_6": "请选择工作能力a",
  "ehr_regular_alert_7": "请选择工作能力b",
  "ehr_regular_alert_8": "请选择工作业绩a",
  "ehr_regular_alert_9": "请选择工作业绩b",
  "ehr_regular_alert_10": "请选择团队精神a",
  "ehr_regular_alert_11": "请选择团队精神b",
  "ehr_regular_alert_12": "请选择团队精神c",
  "ehr_regular_alert_13": "请选择团队精神d",
  "ehr_regular_alert_14": "请填写考核成绩",
  "ehr_regular_alert_15": "请填写评估意见",
  "ehr_regular_alert_16": "请填写当前基本工资",
  "ehr_regular_alert_17": "请填写当前技能工资",
  "ehr_regular_alert_18": "请填写约定转正基本工资",
  "ehr_regular_alert_19": "请填写入职转正约定",
  "ehr_regular_alert_20": "请填写转正基本工资",
  "ehr_regular_alert_21": "请填写转正技能工资",
  "ehr_regular_alert_22": "请选择币种",
  "ehr_regular_alert_23": "请选择转正职级",
  "ehr_regular_alert_24": "请填写转正日期",
  "ehr_regular_alert_25": "请选择期权发放形式",
  "ehr_regular_alert_26": "请选绩效",
  "oa_alert_response_null": "网络连接异常，请检查您的网络",
  "oa_error_status_403": "您沒有权限，请求被拒绝",
  "oa_error_system_info": "系统异常",
  "oa_error_status_1001": "Http必须POST请求",
  "oa_error_status_1002": "URL格式错误",
  "oa_error_status_1003": "缺失必要参数access_token",
  "oa_error_status_1004": "access_token未注册",
  "oa_error_status_1005": "access_token已过期",
  "oa_error_status_1006": "service code未注册",
  "oa_error_status_1007": "access_token对应的用户无权限访问该接口",
  "oa_error_status_1008": "URL创建失败",
  "oa_error_status_1009": "创建Token，提供openid或openkey错误",
  "oa_error_status_1010": "创建Token失败，数据库中未找到对应记录",
  "oa_error_status_1011": "刷新Token失败，数据库中未找到对应记录",
  "oa_error_status_400": "服务器域名解析失败",
  "oa_error_status_406": "超过服务配置的瞬时并发限制",
  "oa_error_status_408": "服务器端口不通",
  "oa_error_status_504": "服务器返回超时",
  "OA_fixedassertallocationdetail_text_model": "规格/型号/资产编号",
  "OA_oneCommit_warning": "不能重复提交！",
  "oa_copy_success": "内容已经复制到剪贴板",
  "OA_costaccountdetail_text_overtime": "夜间交通费",
  "OA_costaccountdetail_text_workinghours": "考勤记录",
  "oa_yes": "是",
  "oa_no": "否",
  "OA_text_usedate": "申请日期",
  "OA_Salary_text_unitprice": "申请金额",
  "OA_Salary_text_residualvalue": "报销金额",
  "OA_text_payment_payee": "收款单位(人)",
  "OA_travel_card_reimbursement": "差旅卡报销",
  "ehr_Intern_p_SXSLYSQPGB": "实习生留用申请评估表",
  "ehr_Intern_p_basicinfo": "基本信息",
  "ehr_Intern_p_process": "审批流程",
  "ehr_Intern_p_SXS": "实习生",
  "ehr_Intern_p_SQSJ": "申请时间",
  "ehr_Intern_p_SQBM": "申请部门",
  "ehr_Intern_p_DSYG": "导师员工",
  "ehr_Intern_p_GW": "岗位",
  "ehr_Intern_p_RZRQ": "入职日期",
  "ehr_Intern_p_SJGZSJ": "实际工作时间",
  "ehr_Intern_p_QZRQ": "最高学历起止时间",
  "ehr_Intern_p_XXMC": "学校名称",
  "ehr_Intern_p_ZY": "专业",
  "ehr_Intern_p_XLLX": "学历类型",
  "OA_item_total_amount": "项目总金额",
  "OA_recipient_itemdetail_text_item": "收单单位(人)",
  "OA_recipient_itemdetail_text_account": "收款帐号",
  "OA_recipient_itemdetail_text_bankName": "开户行",
  "OA_recipient_itemdetail_text_city": "开户城市",
  "OA_recipient_itemdetail_text_cashPledgeAmount": "押金付款金额",
  "OA_recipient_itemdetail_text_contractPaymentAmount": "合同付款金额",
  "OA_additemdetail_text_paymentdetail": "支付明细",
  "OA_itemDetail_text_contractPaymentAmount": "付款金额",
  "OA_itemDetail_text_bankAddress": "开户行地址",
  "OA_no_Down_Title": '无法下载',
  "OA_no_Down_Tips": '手机端暂不支持该格式文件的下载，请前往PC端对应待审批单据下载',
  "OA_detail_business_type": '业务分组',
  "OA_detail_business_type_placeholder":'业务分组查询',
}


const lang_EN = {
  "OA_index_share_title": 'OA小程序',
  "OA_index_share_content": '点击进入oa小程序',


  "OA_itemDetail_text_bankAddress": "Bank Address",
  "OA_Form_Detail_Residue": 'residue',
  "OA_no_message": "Data is Empty",
  "OA_loading_text":"Loading...",
  "OA_index_link_waitapproval": "Pending",
  "OA_index_link_submitted": "Submitted",
  "OA_index_link_reimbursement": "Reimbursement",
  "OA_index_link_businesstravel": "Businesstravel",
  "OA_index_link_budget": "Budget",
  "OA_index_link_authorize": "Authorize",
  "OA_index_link_taxnumber": "Taxnumber",
  "OA_index_alert_authorization": "NO Permission",
  "OA_index_alert_network": "Network error",
  "OA_index_alert_data": "Data error",
  "OA_index_alert_confirm": "Confirm",
  "OA_index_alert_prompt": "Prompt",

  "OA_notice_title_my_taxnumber": "My Taxnumber",
  "OA_notice_title_taxnumber": "FinanceTaxnumber",
  "OA_notice_text_company": "Company:",
  "OA_notice_text_taxnumber": "TaxNum:",
  "OA_notice_text_bankaccount": "A/C NO:",
  "OA_notice_text_bankname": "BankName:",
  "OA_notice_text_telephone": "Tel:",
  "OA_notice_text_address": "Address:",

  "OA_formlist_btn_my_approval": "My Approval",
  "OA_formlist_btn_my_submitted": "My Submitted",
  "OA_formlist_btn_waitapproval": "Pending",
  "OA_formlist_btn_approved": "Approved",
  "OA_formlist_btn_submitted": "Submitted",
  "OA_formlist_btn_orderbytime": "Time",
  "OA_formlist_btn_orderbytype": "Category",
  "OA_formlist_btn_orderbysubmitter": "Submitter",
  "OA_formlist_btn_orderbypriority": "Priority",
  "OA_formlist_btn_priority": "Sort",
  "OA_formlist_btn_cancel": "Cancel",
  "OA_formlist_btn_search": "Search",
  "OA_formlist_btn_approving": "Approving",
  "OA_formlist_text_counts": "50 most",
  "OA_formlist_OA_number": "OA Number",
  "OA_formlist_OA_data_submit": "Date of submittion",
  "OA_formlist_text_prompt_submit":"No requests in recent 3 months",
  "OA_formlist_text_prompt": "No forms to approve in recent 3 months",
  "OA_formlist_text_noapproval":"No Pending Requests",
  "OA_oaFormList_alert_network": "Network error",
  "OA_oaFormList_alert_prompt": "Prompt",
  "OA_oaFormList_alert_confirm": "Confirm",
  "OA_oaFormList_alert_effect": "Effect",
  "OA_oaFormList_alert_refused": "Refused",
  "OA_formlist_btn_searchdetail": "Subject/Submitter/Code",
  "OA_formlist_btn_refresh": "Refresh",
  "OA_costaccount_text_fill": "Expense Reimbursement Form",
  "OA_costaccount_text_basic_information": "Basic Information",
  "OA_costaccount_text_account_information": "Account Information",
  "OA_costaccount_text_travel_information": "Business Trip Information",
  "OA_costaccount_text_formtype": "FormType",
  "OA_costaccount_text_unit": "Unit",
  "OA_costaccount_text_budgettype": "BudgetType",
  "OA_costaccount_text_costcenter": "CostCenter",
  "OA_costaccount_text_paymentcompany": "PaymentCompany",
  "OA_costaccount_text_payee": "Payee",
  "OA_costaccount_text_receiptaccount": "ReceiptAccount",
  "OA_costaccount_text_receiptaccount_tip": "Please enter Payee account number",
  "OA_costaccount_text_bankname": "BnakName",
  "OA_costaccount_text_bankname_tip": "Please input BnakName",
  "OA_costaccount_text_cityofbank": "City",
  "OA_costaccount_text_cityofbank_tip": "Please enter Bank account location - city",
  "OA_costaccount_text_number_invoices": "Please enter Number of invoices",
  "OA_costaccount_text_numberofinvoice": "Invoices'number",
  "OA_costaccount_text_Apportionmentmonth": "Budget month",
  "OA_costaccount_text_budgetclassification": "Budget classification",
  "OA_costaccount_text_remarks": "Remarks",
  "OA_costaccount_text_next": "Next",
  "OA_costaccount_text_prompt": "APP only supports single cost center, single budget classifications Expense reimbursement form",
  "OA_costaccount_text_limited": "Limited to 800 charecters most",
  "OA_Newcostaccount_alert_fill": "With * can not be empty!",
  "OA_Newcostaccount_alert_invoice": "The  number of invoices must be positive integer.",
  "OA_Newcostaccount_text_formtype": "Expense Reimbursement Form",
  "OA_Newcostaccount_text_costcenterorbudgettype": "Single Costcenter and BudgetType",
  "OA_Newcostaccount_alert_network": "Network Error",
  "OA_Newcostaccount_alert_prompt": "Prompt",
  "OA_Newcostaccount_alert_confirm": "Confirm",
  "OA_additemdetail_text_itemdetail": "Itemdetail",
  "OA_recipient_item_detail": "recipientItemDetail",
  "OA_additemdetail_btn_add": "Add",
  "OA_additemdetail_text_itemdetailtotalamount": "TotalAmount",
  "OA_additemdetail_text_item": "Item",
  "OA_additemdetail_text_date": "Date",
  "OA_additemdetail_text_amount": "Amount",
  "OA_additemdetail_text_explanation": "Reason",
  "OA_additemdetail_content_prompt": "No itemdetail, Please add first.",
  "OA_additemdetail_btn_back": "Back",
  "OA_additemdetail_btn_submit": "Submit",
  "OA_additemdetail_btn_submitting": "Submitting",
  "OA_AddItemDetail_alert_fill": "With * can not be empty!",
  "OA_AddItemDetail_alert_AddPrompt": "Prompt",
  "OA_AddItemDetail_alert_cancel": "Cancel",
  "OA_AddItemDetail_alert_confirm": "Confirm",
  "OA_AddItemDetail_alert_addsucessful": "Successfully added",
  "OA_AddItemDetail_alert_network": "Network Error",
  "OA_AddItemDetail_alert_ConfirmSubmit": "Are you sure to submit?",
  "OA_AddItemDetail_alert_ConfirmSubmit_Error": "Submit Error",
  "OA_AddItemDetail_alert_FormatofAmount": "The format of amout is incorrect!",
  "OA_AddItemDetail_alert_Confirmdelete": "Are you sure to delete?",
  "OA_AddItemDetail_alert_Prompt": "Prompt",
  "OA_itemDetailModal_text_itemdetail": "Itemdetail",
  "OA_itemDetailModal_text_item": "Item",
  "OA_itemDetailModal_text_startdate": "StartDate",
  "OA_itemDetailModal_text_amount": "Amount",
  "OA_itemDetailModal_text_explanation": "Reason",
  "OA_itemDetailModal_btn_add": "Add",
  "OA_itemDetailModal_btn_select": "Please select",
  "OA_itemDetailModal_text_limited": "Limited to 800 charecters most.",
  "OA_travelaccount_text_prompt": "The mobile only supports single expense center, single budget classification, and no monthly expense reimbursement form",
  "OA_travelaccount_text_formtype": "Formtype",
  "OA_travelaccount_text_unit": "Unit",
  "OA_travelaccount_text_budgettype": "BudgetType",
  "OA_travelaccount_text_costcenter": "CostCenter",
  "OA_travelaccount_text_paymentcompany": "Paymentcompany",
  "OA_travelaccount_text_startdate": "StartDate",
  "OA_travelaccount_text_enddate": "EndDate",
  "OA_travelaccount_text_address": "Address",
  "OA_travelaccount_text_address_place": "Please enter Business Trip Loction",
  "OA_travelaccount_text_reason": "Reason",
  "OA_travelaccount_text_payee": "Payee",
  "OA_travelaccount_text_payee_name": "Please enter Payee",
  "OA_travelaccount_text_receiptaccount": "ReceiptAccount",
  "OA_travelaccount_text_bankname": "BankName",
  "OA_travelaccount_text_cityofbank": "CityofBank",
  "OA_travelaccount_text_numberofinvoice": "Invoice NO.",
  "OA_travelaccount_text_Apportionmentmonth": "Apportionment month",
  "OA_travelaccount_text_budgetclassification": "BudgetClassification",
  "OA_travelaccount_text_select_budgettype": "Budget classification inquiry",
  "OA_travelaccount_text_company_inquiry": "Payment company inquiry",
  "OA_travelaccount_text_remarks": "Remarks",
  "OA_travelaccount_text_next": "Next",
  "OA_travelItem_text_itemdetail": "ItemDetail",
  "OA_travelItem_btn_add": "Add",
  "OA_travelItem_text_ItemdetailtotalAmount": "TotalAmount",
  "OA_travelItem_text_item": "Item",
  "OA_travelItem_text_amount": "Amount",
  "OA_travelItem_text_explanation": "Reason",
  "OA_travelItem_text_prompt": "No itemdetail, Please add first.",
  "OA_travelItem_btn_back": "Back",
  "OA_travelItem_btn_submit": "Submit",
  "OA_travelitemDetailModal_text_choose": "Please select",
  "OA_travelitemDetailModal_text_itemdetail": "ItemDetail",
  "OA_travelitemDetailModal_text_item": "Item",
  "OA_travelitemDetailModal_text_select": "Please select",
  "OA_travelitemDetailModal_text_Amount": "Amount",
  "OA_travelitemDetailModal_text_explanation": "Reason",
  "OA_travelitemDetailModal_btn_add": "Add",
  "OA_travelaccount_text_fill": "Travel Expense Reimbursement",
  "OA_NewtravelAccount_alert_date": "The end date  must be later than start date!",
  "OA_NewtravelAccount_alert_warning": "Warning",
  "OA_NewtravelAccount_alert_fill": "With * can not be empty!",
  "OA_NewtravelAccount_text_formtype": "Travel Expense Reimbursement Form",
  "OA_NewtravelAccount_text_costcenterorbudgettype": "Single Costcenter and BudgetType",
  "OA_NewtravelAccount_alert_network": "Network error",
  "OA_NewtravelAccount_alert_prompt": "Prompt",
  "OA_NewtravelAccount_alert_confirm": "Confirm",
  "OA_NewtravelItem_alert_added": "The item has already been added. ",
  "OA_NewtravelItem_alert_itemdetail": "Please add item detail.",
  "OA_NewtravelItem_alert_prompt": "prompt",
  "OA_NewtravelItem_alert_cancel": "Cancel",
  "OA_NewtravelItem_alert_Confirm": "Confirm",
  "OA_NewtravelItem_alert_AddedSuccessfully": "Added Successfully!",
  "OA_NewtravelItem_alert_network": "Network error",
  "OA_NewtravelItem_list_flightandcar": "Air or car tickets",
  "OA_NewtravelItem_list_airconstructionfee": "Airport Construction Fee",
  "OA_NewtravelItem_list_taxi": "Taxi",
  "OA_NewtravelItem_list_hotel": "Hotel",
  "OA_NewtravelItem_list_Hospitality": "Hospitality Fee",
  "OA_NewtravelItem_list_correspondence": "Correspondence Fee",
  "OA_NewtravelItem_list_Conference": "Conference Fee",
  "OA_NewtravelItem_list_Miscellaneous": "Miscellaneous fees",
  "OA_NewtravelItem_list_Gift": "Gift",
  "OA_NewtravelItem_list_others": "Others",
  "OA_NewtravelItem_list_formatofAmount": "The format of amout is incorrect!",
  "OA_travelaccount_text_select": "Please select",
  "OA_travelaccount_text_Limited": "Limited to 800 charecters most.",
  "OA_NewtravelAccount_alert_formatofinvoice": "The  number of invoices must be positive integer.",
  "OA_NewtravelItem_open": "Unfold",
  "OA_NewtravelItem_close": "Fold",
  "OA_authListCtrl_status_NotStarted": "NotStarted",
  "OA_authListCtrl_status_ongoing": "ongoing",
  "OA_authListCtrl_status_completed": "completed",
  "OA_authListCtrl_btn_Enabled": "Enabled",
  "OA_authListCtrl_btn_Disabled": "Disabled",
  "OA_authlist_text_authorization": "Authorization",
  "OA_authlist_alert_refreash": "Down to Refreash",
  "OA_authlist_text_startdate": "StartDate",
  "OA_authlist_text_enddate": "EndDate",
  "OA_authlist_alert_counts": "No Authorized records in recent 3 months.",
  "OA_authupdateAndAdd_text_startdate": "StartDate",
  "OA_authupdateAndAdd_text_select": "Please select",
  "OA_authupdateAndAdd_text_enddate": "EndDate",
  "OA_authupdateAndAdd_text_agent": "Agent",
  "OA_authupdateAndAdd_text_delete": "Delete",
  "OA_authupdateAndAdd_text_update": "Update",
  "OA_authupdateAndAdd_text_authorize": "Authorize",
  "OA_authupdateAndAdd_text_authorize_history": "Authorized records",
  "OA_authupdateAndAdd_text_search": "Fullname or Firstname",
  "OA_authUpdateAndAddCtrl_text_add": "Add authorization",
  "OA_authUpdateAndAddCtrl_text_update": "Update",
  "OA_authUpdateAndAddCtrl_text_end":"End",
  "OA_authUpdateAndAddCtrl_alert_prompt": "Prompt",
  "OA_authUpdateAndAddCtrl_alert_confirm": "Confirm",
  "OA_authUpdateAndAddCtrl_alert_enable": "Enabled",
  "OA_authUpdateAndAddCtrl_alert_updatefailed": "Update Failed",
  "OA_authUpdateAndAddCtrl_alert_deletefailed": "Delate Failed",
  "OA_authUpdateAndAddCtrl_alert_warning": "Warning",
  "OA_authUpdateAndAddCtrl_alert_confirmdelete": "Are you sure to delete?",
  "OA_authUpdateAndAddCtrl_alert_confirmend": "Are you sure to end?",
  "OA_authUpdateAndAddCtrl_alert_cancel": "Cancel",
  "OA_authUpdateAndAddCtrl_alert_confirm": "Confirm",
  "OA_authUpdateAndAddCtrl_alert_selectstartdate": "Please select startdate",
  "OA_authUpdateAndAddCtrl_alert_selectenddate": "Please select enddate",
  "OA_authUpdateAndAddCtrl_alert_selectagent": "Please select agent",
  "OA_authUpdateAndAddCtrl_alert_authorizefailed": "Authorize Failed",
  "OA_authupdateAndAdd_text_choose": "Please select",
  "OA_addpointsapplydetail_text_formdetail": "Form detail",
  "OA_addpointsapplydetail_alert_refreash": "Down to Refreash",
  "OA_addpointsapplydetail_text_operator": "Operator",
  "OA_addpointsapplydetail_text_applynumber": "OA Number",
  "OA_addpointsapplydetail_text_applytime": "Apply time",
  "OA_addpointsapplydetail_text_applystatus": "Status",
  "OA_addpointsapplydetail_text_approving": "Approving",
  "OA_addpointsapplydetail_text_Expectedapprovers": "Expected approvers",
  "OA_addpointsapplydetail_text_Costcenter": "Costcenter",
  "OA_addpointsapplydetail_text_itemname": "Itemname",
  "OA_addpointsapplydetail_text_itemnumber": "Itemnumber",
  "OA_addpointsapplydetail_text_totalpoints": "Totalpoints",
  "OA_addpointsapplydetail_text_amount": "Totalcost",
  "OA_addpointsapplydetail_text_remark": "Remark",
  "OA_addpointsapplydetail_text_attachment": "Attachments",
  "OA_addpointsapplydetail_text_workflowlog": "Workflowlogs",
  "OA_AddPointsApplyDetailCtrl_text_explanation": "Explanation",
  "OA_AddPointsApplyDetailCtrl_text_approval comments": "Please fill in approval comments",
  "OA_AddPointsApplyDetailCtrl_text_approval explanationRequired": "Explanation(Required)",
  "OA_AddPointsApplyDetailCtrl_text_refuse": "Refuse",
  "OA_AddPointsApplyDetailCtrl_text_ReasontoRefuse": "Please fill in the reason for refusing",
  "OA_AddPointsApplyDetailCtrl_text_NoMoreForms": "Approval has been completed. Please refresh and continue",
  "OA_businesscardprintingdetail_text_companyChinese": "biz_company_cn",
  "OA_businesscardprintingdetail_text_companyEnglish": "biz_company_en",
  "OA_businesscardprintingdetail_text_nameChinese": "applicant_name_cn",
  "OA_businesscardprintingdetail_text_nameEnglish": "applicant_name_en",
  "OA_businesscardprintingdetail_text_positionChinese": "position_cn",
  "OA_businesscardprintingdetail_text_positionEnglish": "position_en",
  "OA_businesscardprintingdetail_text_departmentChinese": "Dept_cn",
  "OA_businesscardprintingdetail_text_departmentEnglish": "Dept_en",
  "OA_businesscardprintingdetail_text_addressChinese": "Addr_cn",
  "OA_businesscardprintingdetail_text_addressEnglish": "Addr_en",
  "OA_businesscardprintingdetail_text_officetelphone": "Office_telephone",
  "OA_businesscardprintingdetail_text_officefaxnumber": "Fax_telephone",
  "OA_businesscardprintingdetail_text_mobilephone": "Mobile_phone",
  "OA_businesscardprintingdetail_text_email": "E_mail",
  "OA_businesscardprintingdetail_text_wechatID": "Personal_wechat",
  "OA_businesscardprintingdetail_text_numberofboxes": "Apply_number",
  "OA_chapterBusinessdetail_text_chapter_company": "Company",
  "OA_chapterBusinessdetail_text_chapter_department": "Dept.",
  "OA_chapterBusinessdetail_text_chapter_reason": "Apply reason",
  "OA_ChapterInvestmentdetail_text_filetype": "Filetype",
  "OA_ChapterInvestmentdetail_text_reason": "Reason",
  "OA_ChapterSealEngravingdetai_text_stamper_usefor": "Stamper_usefor",
  "OA_ChapterSealEngravingdetai_text_stamper_unit": "Stamper_unit",
  "OA_ChapterSealEngravingdetai_text_stamper_content": "Stamper_content",
  "OA_ChapterSealEngravingdetai_text_remark": "Remark",
  "OA_contractpaymentdetail_text_paymentpayee": "Payee",
  "OA_contractpaymentdetail_text_contractnumber": "Contract number",
  "OA_contractpaymentdetail_text_totalcontractamount": "Total contract amount",
  "OA_contractpaymentdetail_text_unsure": "Unsure",
  "OA_contractpaymentdetail_text_amountpaid": "Amount paid",
  "OA_contractpaymentdetail_text_amountpaidforthistime": "Amount paid this time",
  "OA_contractpaymentdetail_text_amountpaidforthistimeRMB": "RMB",
  "OA_contractpaymentdetail_text_depositforthistime": "Deposit amount this time",
  "OA_contractpaymentdetail_text_depositforthistimeRMB": "RMB",
  "OA_contractpaymentdetail_text_depositoffsetforthistime": "Deposit offset this time",
  "OA_contractpaymentdetail_text_depositoffsetforthistimeRMB": "RMB",
  "OA_contractpaymentdetail_text_paymentbalance": "Overdraft balance",
  "OA_contractpaymentdetail_text_paymentreason": "Payment reason",
  "OA_contractpaymentdetail_text_allocationtime": "Budget allocation time",
  "OA_contractpaymentdetail_text_budgetproportion": "Budget ratio",
  "OA_contractpaymentdetail_text_multiplecostcenter": "Multiple costcenter",
  "OA_costaccountdetail_text_expensetype": "Expense type",
  "OA_costaccountdetail_text_totalamount": "Total amount",
  "OA_costaccountdetail_text_dateofoccurance": "Date",
  "OA_costaccountcontroller_text_prompt": "Please add item on computer first",
  "OA_costticketsapplydetail_text_tickettype": "Coupons'type",
  "OA_costticketsapplydetail_text_ticketform": "Coupons'form",
  "OA_costticketsapplydetail_text_ticketnumber": "Coupons'number",
  "OA_costticketsapplydetail_text_dateofeffect": "Date of effect",
  "OA_costticketsapplydetail_text_ticketname": "Coupons'name",
  "OA_costticketsapplydetail_text_ticketnature": "Coupons'nature",
  "OA_costticketsapplydetail_text_amount": "Released amount",
  "OA_costticketsapplydetail_text_expectedcost": "Estimated cost",
  "OA_costticketsapplydetail_text_expecteduserate": "Estimated use rate",
  "OA_couponapplydetail_text_couponsnumber": "Coupons number",
  "OA_delieverydetail_text_recipientaddress": "Recipient address",
  "OA_delieverydetail_text_recipientname": "Recipient name",
  "OA_delieverydetail_text_recipientphone": "Recipient phone",
  "OA_delieverydetail_text_carrier": "Carrier",
  "OA_delieverydetail_text_waybillnumber": "Waybill number",
  "OA_delieverydetail_text_expresstype": "Express type",
  "OA_delieverydetail_text_expressdetail": "Express detail",
  "OA_devicepurchasedetail_text_model": "Model",
  "OA_devicepurchasedetail_text_quantity": "Quantity",
  "OA_devicepurchasedetail_text_unitprice": "Amount",
  "OA_devicepurchasedetail_text_totalprice": "Totalprice",
  "OA_devicepurchasedetail_text_explanation": "Explanation",
  "OA_devicepurchasedetail_text_auditdepartment": "Audit Dept.",
  "OA_fixedassertallocationdetail_text_Affiliatedcompany": "Affiliated Co.",
  "OA_fixedassertallocationdetail_text_fromdepartment": "Dept.(from)",
  "OA_fixedassertallocationdetail_text_todepartment": "Dept.(to)",
  "OA_fixedassertallocationdetail_text_assettype": "Asset type",
  "OA_fixedassertallocationdetail_text_assetnumber": "Asset number",
  "OA_fixedassertallocationdetail_text_usedate": "Asset usedate",
  "OA_fixedassertallocationdetail_text_place": "Asset site",
  "OA_fixedassetsapplydetail_text_receiptdepartment": "Receipt Dept.",
  "OA_fixedassetsapplydetail_text_auditnumber": "Audit number",
  "OA_fixedassetsscrappeddetail_text_scrappeddepartment": "Scrapped Dept.",
  "OA_fixedassetsscrappeddetail_text_residualvalue": "Actual amount",
  "OA_formbutton_btn_countersign": "Countersign",
  "OA_formbutton_btn_approval": "Approval",
  "OA_formbutton_btn_refuse": "Refuse",
  "OA_formbutton_btn_next": "Next",
  "OA_giftcollardetail_text_customername": "Customer name",
  "OA_giftcollardetail_text_applyforuse": "Apply for use",
  "OA_giftcollardetail_text_giftdetail": "Gift detail",
  "OA_giftcollardetail_text_giftname": "Gift name",
  "OA_giftcollardetail_text_listofitems": "List of items",
  "OA_incomecontractreviewdetail_text_contractingcompany": "Contracting Co.",
  "OA_incomecontractreviewdetail_text_contractnumber": "Contract number",
  "OA_incomecontractreviewdetail_text_contractname": "Contract name",
  "OA_incomecontractreviewdetail_text_agreementunit": "Agreement unit",
  "OA_incomecontractreviewdetail_text_contractamount": "Contract amount",
  "OA_incomecontractreviewdetail_text_contractdeposit": "Contract deposit",
  "OA_incomecontractreviewdetail_text_keyword": "Keyword",
  "OA_incometicketsapplydetail_text_couponsissuingcompany": "Issuing company",
  "OA_incometicketsapplydetail_text_couponsdiscountrate": " Discount rate",
  "OA_incometicketsapplydetail_text_couponsactualreceipt": "Actual receipts",
  "OA_incometicketsapplydetail_text_limit": "Contract Term",
  "OA_letterdetail_text_letterdetai": "Letter detail",
  "OA_letterdetail_text_letteritemdetai": "Letter itemdetail",
  "OA_letterdetail_text_totalquantity": "Total quantity",
  "OA_letterdetail_text_lettertype": "Letter type",
  "OA_MICEgroupapplydetail_text_miceteamnumer": "TeamNumber",
  "OA_MICEgroupapplydetail_text_miceteamamount": "TeamAmount",
  "OA_joinerctrl_alert_timeout": "Time out.",
  "OA_joinerctrl_alert_chooseotherperson": "countersignature can not be yourself.",
  "OA_joinerctrl_alert_alreadychoosed": "You have already countersigned  the person.",
  "OA_joinerctrl_alert_choosesomeone": "Please choose someone to countersign.",
  "OA_joiner_text_add": "Add countersignature",
  "OA_joiner_text_name": "Added list",
  "OA_joiner_text_addhistory": "Added history",
  "OA_joiner_text_addedlist": "Please fill in the reason for countersigning.",
  "OA_joiner_text_add_prompt": "Null is forbidden",
  "OA_joiner_text_select": "Optional",
  "OA_officesuppliescollardetail_text_itemname": "Itemname",
  "OA_officesuppliescollardetail_text_officesuppliesdetail": "Office supplies detail",
  "OA_pointspolicyapply_text_integralname": "Integral name",
  "OA_pointspolicyapply_text_integraltype": "Integral type",
  "OA_pointspolicyapply_text_releasedintegral": "Total points",
  "OA_pointspolicyapply_text_expectedintegral": "Expected annual points ",
  "OA_pointspolicyapply_text_integralrule": "Integral rule",
  "OA_purchasecontractreview_text_vendor": "Vendor",
  "OA_sendcardetail_text_usecarreason": "Use reason",
  "OA_sendcardetail_text_usecardetail": "Sendcar detail",
  "OA_sendcardetail_text_usecardate": "Use Date",
  "OA_sendcardetail_text_usecarorigin": "Origin",
  "OA_sendcardetail_text_usecardestination": "Destination",
  "OA_staffloandetail_text_applyamount": "Application amount",
  "OA_feereport_text_feepeport": "Fee report",
  "OA_feereportCtrl_text_used": "Used",
  "OA_feereportCtrl_text_unused": "Unused",
  "OA_feereportCtrl_text_costrate": "Fee ratio",
  "OA_feereportCtrl_text_withoutbudget": "Without budget",
  "OA_feereportCtrl_text_Errorofbudget": "Error with accessing budget of cost center",
  "OA_feereportCtrl_budgettop10": "Budget Top10",
  "OA_feereportCtrl_text_Errorofallbudget": "Error with accessing all variety of budget of cost center",
  "OA_feereportCtrl_personalfeetop10": "Personal fee Top10",
  "OA_feereportCtrl_text_Erroroffee": "Error with accessing fee of cost center",
  "OA_feereportCtrl_text_Q1costrate": "Q1 fee ratio",
  "OA_feereportCtrl_text_userate": "Use rate",
  "OA_feereportCtrl_text_totalbudget": "Total budget: ",
  "OA_feereportCtrl_text_usedrate": "Used rate：",
  "OA_feereportCtrl_text_year": "-",
  "OA_feereportCtrl_text_month":" ",
  "OA_applyapproval_text_countersign": "Add countersign",
  "OA_applyapproval_text_searchcountersign": "Search countersign",
  "OA_formdetail_text_viewexpectedapprovers": "View expected approvers",
  "eform_warning": "warn",
  "eform_network": "no network",
  "eform_title": "Approval",
  "eform_index_tab_all": "All",
  "eform_index_tab_ehr": "EHR",
  "eform_index_refresher": "Drop refresh",
  "eform_index_order_time": "Time",
  "eform_index_order_user": "Applicant",
  "eform_index_order_subject": "Subject",
  "eform_index_span_sign": "allograph",
  "eform_index_span_joinsign": "countersign",
  "eform_index_noapp_tip": "There is no approval form for you at present",
  "eform_index_nooa_tip": "OA not supported，coming soon",
  "eform_index_click_goauth": "Authorization",
  "eform_index_click_goauthlist": "My Authorization",
  "eform_index_toggle_showjoinapp": "show countersign",
  "eform_index_OAgetAgentList_tipinfo": "OA authorization list failed to obtain",
  "eform_index_OAupdateAgent_tipinfo": "OA authorization failed to recover",
  "eform_index_EhrgetAgentList_tipinfo": "EHR authorization list failed to obtain",
  "eform_index_EhrupdateAgent_tipinfo": "EHR authorization failed to recover",
  "eform_index_ITAgent_tipinfo": "IT authorization failed to recover",
  "eform_index_AllAgent_tipinfo": "Your permissions have been fully recovered",
  "eform_it_span_process": "Approval process",
  "eform_it_checkbox_all": "Select",
  "eform_it_checkbox_selected": "Selected",
  "eform_it_checkbox_item": "items",
  "eform_it_btn_joindecline": "Decline",
  "eform_it_btn_joinapprove": "Approve",
  "eform_it_btn_next": "Next",
  "eform_it_btn_signer": "signer",
  "eform_it_btn_decline": "Decline",
  "eform_it_btn_approve": "Approved",
  "eform_it_status_pending": "Pending",
  "eform_it_status_approve": "Approve",
  "eform_it_status_decline": "Decline",
  "eform_it_status_cancel1": "The node has been canceled ",
  "eform_it_status_cancel2": "The higher node has been canceled",
  "eform_it_warn_noselect": "You haven't chosen any documents",
  "eform_it_warn_noreason": "Please enter the reason!",
  "eform_it_warn_goctripteam": "Failed to get jump information!",
  "eform_itjoin_title": "Add signer",
  "eform_itjoin_search_name": "Name",
  "eform_itjoin_search_initials": "Initials",
  "eform_itjoin_search_pinyin": "Pinyin",
  "eform_itjoin_search_ad": "Account",
  "eform_itjoin_search_cancel": "cancel",
  "eform_itjoin_signer_history": "history",
  "eform_itjoin_signer_list": "List added",
  "eform_itjoin_signer_reason": "Please fill in the reasons",
  "eform_itjoin_reason_placeholder": "optional",
  "eform_itjoin_btn_cancel": "Cancel",
  "eform_itjoin_btn_ok": "OK",
  "eform_itjoin_warn_self": "cannot choose yourself as a signer",
  "eform_itjoin_warn_selected": "This person has been selected",
  "eform_itjoin_warn_nosigner": "Please choose signer",
  "eform_ehr_span_leavedate": "Leave date",
  "eform_ehr_span_datehours": "Daily hours",
  "eform_ehr_span_leavedaynum": "Hours of leave",
  "eform_ehr_span_day": "day",
  "eform_ehr_span_hours": "hours",
  "eform_ehr_span_tips": "instruction",
  "eform_ehr_batchApplyTitle": "Leave Application Form",
  "eform_ehr_noAduiterList": "Approval flow is empty!",
  "eform_ehr_status_0": "Pending",
  "eform_ehr_status_1": "Approved",
  "eform_ehr_status_3": "Countersigned",
  "eform_ehr_status_4": "Canceled",
  "eform_ehr_status_5": "Canceled",
  "eform_ehr_AuditerStatus_3": "The document is countersigned。",
  "eform_ehr_sign_comment": "Please fill out your comments",
  "eform_ehr_sign_reason": "Please fill out your reason",
  "eform_remedy_span_Apprvoers": "Approver",
  "eform_remedy_span_Summary": "Summary",
  "eform_remedy_span_Detail": "Description",
  "eform_AccreditList_view_title": " My Authorized",
  "eform_AccreditList_tabs_all": "All",
  "eform_AccreditList_tabs_remedy": "Remedy",
  "eform_AccreditList_refresher_pullingText": "Pull Refresh...",
  "eform_AccreditList_div_noApproving": "There is no authorize records",
  "eform_AccreditList_div_timeUntil": "To",
  "eform_AccreditList_div_deadline": "Deadline",
  "eform_AccreditList_checkbox_all": "Select All",
  "eform_AccreditList_button_takeBack": "Revoke",
  "eform_AccreditListCtrl_item_status": "vaild",
  "eform_AccreditListCtrl_jsListStatus_authIn": "valid",
  "eform_AccreditListCtrl_jsListStatus_unBegin": "Not begin",
  "eform_AccreditListCtrl_jsrole_all": "All Roles",
  "eform_AccreditListCtrl_jsOnDelete_template": "You will revoke this authorization",
  "eform_AccreditListCtrl_jsOnDelete_title": "Reminder",
  "eform_AccreditListCtrl_jsOnDelete_buttonOK": "Revoke",
  "eform_AccreditListCtrl_jsOnDelete_buttonCancel": "Think Again",
  "eform_AccreditListCtrl_jsGetAuthList_callbackError": "Ehr authorization list failed to obtain. Please try again later",
  "eform_AccreditListCtrl_jsAuditAuthorizeQuery_callbackError": "IT authorization list failed to obtain. Please try again later",
  "eform_AccreditListCtrl_jsQueryalternate_statusError": "Remedy authorization list failed to obtain. Please try again later",
  "eform_AccreditListCtrl_jsSelectAll_selectNone": "You didn't select the object",
  "eform_AccreditListCtrl_jsOAupdateAgent_callbackError": "OA authorization failed to revoke. Please try again later",
  "eform_AccreditListCtrl_jsCancelAuth_callbackError": "Ehr authorization failed to revoke. Please try again later",
  "eform_AccreditListCtrl_jsAuditAuthorizeDelete_callbackError": "IT authorization failed to revoke. Please try again later",
  "eform_AccreditListCtrl_jsRemedyCancel_callbackError": "Remedy authorization failed to revoke. Please try again later",
  "eform_AccreditListCtrl_jsWaitDelete_deleteSuccess": "Revoking authority successed",
  "eform_updateAccredit_view_title": "Authorization",
  "eform_updateAccredit_button_submit": "submit",
  "eform_updateAccredit_inputLable_startDate": "Start Date",
  "eform_updateAccredit_p_select": "Please Select",
  "eform_updateAccredit_inputLable_endDate": "End Date",
  "eform_updateAccredit_inputLable_Agent": "Agent",
  "eform_updateAccredit_input_placeholder": "Fullname/Firstname/Account",
  "eform_updateAccredit_span_searchHistory": "Search History",
  "eform_updateAccredit_label_clearSearchHistory": "Clear search history",
  "eform_updateAccredit_div_tip": "*The Agent which filled in the below form  have priority.There are Optional.",
  "eform_accreditCtrl_jsmonthList_Jan": "Jan",
  "eform_accreditCtrl_jsmonthList_Feb": "Feb",
  "eform_accreditCtrl_jsmonthList_Mar": "Mar",
  "eform_accreditCtrl_jsmonthList_Apr": "Apr",
  "eform_accreditCtrl_jsmonthList_May": "May",
  "eform_accreditCtrl_jsmonthList_June": "June",
  "eform_accreditCtrl_jsmonthList_July": "July",
  "eform_accreditCtrl_jsmonthList_Aug": "Aug",
  "eform_accreditCtrl_jsmonthList_Sep": "Sep",
  "eform_accreditCtrl_jsmonthList_Oct": "Oct",
  "eform_accreditCtrl_jsmonthList_Nov": "Nov",
  "eform_accreditCtrl_jsmonthList_Dec": "Dec",
  "eform_accreditCtrl_jsweeklist_Sun": "S",
  "eform_accreditCtrl_jsweeklist_Mon": "M",
  "eform_accreditCtrl_jsweeklist_Tues": "T",
  "eform_accreditCtrl_jsweeklist_Wed": "W",
  "eform_accreditCtrl_jsweeklist_Thur": "T",
  "eform_accreditCtrl_jsweeklist_Fri": "F",
  "eform_accreditCtrl_jsweeklist_Sat": "S",
  "eform_accreditCtrl_jsdatePopup_todayLabel": "Today",
  "eform_accreditCtrl_jsdatePopup_closeLabel": "Cancel",
  "eform_accreditCtrl_jsdatePopup_setLabel": "OK",
  "eform_accreditCtrl_jsAlert_warnTitle": "Warning",
  "eform_accreditCtrl_jsAlert_warnInfo": "The start time must be less than the end time！",
  "eform_accreditCtrl_jsAlert_startPopup": "Start Date",
  "eform_accreditCtrl_jsAlert_endPopup": "End Date",
  "eform_accreditCtrl_jsScope_httpAlert": "Network request timeout!",
  "eform_accreditCtrl_jsPopup_title": "Hint",
  "eform_accreditCtrl_jsTipInfo_noRole": "You have no role to authorize",
  "eform_accreditCtrl_jsTipInfo_busyNetwork": "The network is busy, please wait a moment",
  "eform_accreditCtrl_jsTipInfo_ehrError": "EHR authorization failed. Please try again later",
  "eform_accreditCtrl_jsTipInfo_itError": "IT authorization failed. Please try again later",
  "eform_accreditCtrl_jsTipInfo_oaError": "OA authorization failed. Please try again later",
  "eform_accreditCtrl_jsTipInfo_openLicense": "You didn't open the permissions of the authorization.",
  "eform_accreditCtrl_jsTipInfo_noDate": "Please select date",
  "eform_accreditCtrl_jsTipInfo_noOaAgent": "OA agent,please",
  "eform_accreditCtrl_jsTipInfo_noITAgent": "IT agent,please",
  "eform_accreditCtrl_jsTipInfo_noEhrAgent": "Ehr agent,please",
  "eform_accreditCtrl_jsTipInfo_noRemedyAgent": "Remedy agent,please",
  "eform_accreditCtrl_jsTipInfo_approveSuccess": "Authorization successed",
  "ehr_quit_title": "Pending",
  "ehr_quit_btn_refresh": "Refresh",
  "ehr_quit_p_docutype": "Resignation Application",
  "ehr_quit_p_basicinfo": "Basic Info",
  "ehr_quit_p_approvalinfo": "Approval Info",
  "ehr_quit_p_process": "Workflow",
  "ehr_quit_p_applicant": "Applicant",
  "ehr_quit_p_applyDate": "Apply date",
  "ehr_quit_p_department": "Department",
  "ehr_quit_p_hireValid": "Date of Enrollment",
  "ehr_quit_p_EmpLevel": "Rank",
  "ehr_quit_p_ProbationEndDate": "Trial Period End Date",
  "ehr_quit_p_ContractEndDate": "End Date",
  "ehr_quit_p_QuitType": "Dismissal Reason",
  "ehr_quit_p_PulishID": "Pulish Document NO.",
  "ehr_quit_p_EmpAttribute": "Employment Type",
  "ehr_quit_p_ContractLimit": "Contract Term",
  "ehr_quit_p_QuitStyle": "Termination Reason",
  "ehr_quit_p_QuitReason": "Resignation Reason",
  "ehr_quit_p_IsMakeUp": "Compensatory Dismissal",
  "ehr_quit_p_AvgSalary": "Average monthly salary",
  "ehr_quit_p_AgeReference": "Employment Period",
  "ehr_quit_p_Compensation": "Compensation Amount",
  "ehr_quit_p_MakeUpType": "Compensation Reason",
  "ehr_quit_p_MakeUpProcess": "Calculate Compensation",
  "ehr_quit_p_QuitRemark": "Remarks",
  "ehr_quit_p_EmpType": "Classification",
  "ehr_quit_p_Injury": "Injury Information",
  "ehr_quit_p_ItemList": "Handover Checklist",
  "ehr_quit_btn_Pass": "Pass",
  "ehr_quit_btn_AddCounter": "signer",
  "ehr_quit_btn_Refuse": "Refuse",
  "ehr_quit_btn_ReApplicant": "Return to the applicant",
  "ehr_quit_btn_ReApproval": "Return to the previous",
  "ehr_quit_label_IsCompetition": "implement Competition Agreement or not",
  "ehr_quit_label_QuitCode": "Resignation Code",
  "ehr_quit_label_QuitReaonRemark": "Resignation reason remarks",
  "ehr_quit_label_HRNotes": "HR Remarks",
  "ehr_quit_label_AccCloseDate": "Account close date",
  "ehr_quit_label_TerminationMonth": "Month of last day",
  "ehr_quit_label_IsCardReturn": "Access Card",
  "ehr_quit_label_IsHandBook": "Employee Manual",
  "ehr_quit_label_select": "Please select",
  "ehr_quit_jsalert_warn": "warn",
  "ehr_quit_jsalert_Network": "no network",
  "ehr_quit_jsalert_noAduiterList": "Approval flow is empty",
  "ehr_quit_jstext_Status0": "Pending",
  "ehr_quit_jstext_Status1": "Approved",
  "ehr_quit_jstext_Status3": "Countersigned",
  "ehr_quit_jstext_Status4": "Canceled",
  "ehr_quit_jstext_Status5": "Canceled",
  "ehr_quit_jsalert_min": "Date need be after",
  "ehr_quit_jsalert_max": "Date need start",
  "ehr_quit_jsdate_Jan": "Jan",
  "ehr_quit_jsdate_Feb": "Feb",
  "ehr_quit_jsdate_Mar": "Mar",
  "ehr_quit_jsdate_Apr": "Apr",
  "ehr_quit_jsdate_May": "May",
  "ehr_quit_jsdate_June": "June",
  "ehr_quit_jsdate_July": "July",
  "ehr_quit_jsdate_Aug": "Aug",
  "ehr_quit_jsdate_Sep": "Sep",
  "ehr_quit_jsdate_Oct": "Oct",
  "ehr_quit_jsdate_Nov": "Nov",
  "ehr_quit_jsdate_Dec": "Dec",
  "ehr_quit_jsdate_Sun": "S",
  "ehr_quit_jsdate_Mon": "M",
  "ehr_quit_jsdate_Tues": "T",
  "ehr_quit_jsdate_Wed": "W",
  "ehr_quit_jsdate_Thur": "T",
  "ehr_quit_jsdate_Fri": "F",
  "ehr_quit_jsdate_Sat": "S",
  "ehr_quit_jsdate_selectDate": "select date",
  "ehr_quit_jsdate_todayLabel": "Today",
  "ehr_quit_jsalert_cancel": "Cancel",
  "ehr_quit_jsalert_confirm": "Confirm",
  "ehr_quit_jsalert_IsCompetition": "Please select if a Non-Competition Agreement will be implemented.",
  "ehr_quit_jsalert_QuitCode": "Please select Resignation Code",
  "ehr_quit_jsalert_QuitReaonRemark": "Resignation reason remarks",
  "ehr_quit_jsalert_HRNotes": "HR Remarks",
  "ehr_quit_jsalert_AccCloseDate": "Please select the Account close date.",
  "ehr_quit_jsalert_TerminationMonth": "Please select the Month of last day of employment.",
  "ehr_quit_jsalert_success": "success",
  "ehr_quit_jsalert_comment": "Please fill out your comments",
  "ehr_quit_jsalert_ispass": "Are you sure you want approve?",
  "ehr_quit_jsalert_isRefuse": "Are you sure you want refuse?",
  "ehr_quit_jsalert_reason": "Please fill out your reason",
  "ehr_quit_label_SJLZRQ": "Last day of employment",
  "ehr_quit_label_QXZSJLZRQ": "Please select the last day of employment.",
  "ehr_quit_label_QYWHSC": "Ctrip Culture Manual",
  "ehr_quit_p_BZ": "Currency",
  "ehr_addCountersign_title": "Add signer",
  "ehr_addCountersign_search_name": "Name",
  "ehr_addCountersign_search_initials": "Initials",
  "ehr_addCountersign_search_pinyin": "Pinyin",
  "ehr_addCountersign_search_ad": "Account",
  "ehr_addCountersign_search_cancel": "cancel",
  "ehr_addCountersign_signer_history": "history",
  "ehr_addCountersign_signer_list": "List added",
  "ehr_addCountersign_signer_reason": "Please fill in the reasons",
  "ehr_addCountersign_reason_placeholder": "optional",
  "ehr_addCountersign_btn_cancel": "Cancel",
  "ehr_addCountersign_btn_ok": "OK",
  "ehr_addCountersign_warn_self": "cannot choose yourself as a signer",
  "ehr_addCountersign_warn_selected": "This person has been selected",
  "ehr_addCountersign_warn_nosigner": "Please choose signer",
  "ehr_addCountersign_warn_warning": "warn",
  "ehr_addCountersign_warn_network": "no network",
  "ehr_addCountersign_jsalert_success": "success",
  "ehr_transferApplication_title": "Pending",
  "ehr_transferApplication_btn_refresh": "Refresh",
  "ehr_transferApplication_p_docutype": "Transfer Application",
  "ehr_transferApplication_p_basicinfo": "Basic Info",
  "ehr_transferApplication_p_process": "Workflow",
  "ehr_transferApplication_p_applicant": "Applicant",
  "ehr_transferApplication_p_applyDate": "Apply date",
  "ehr_transferApplication_p_TransferEmp": "Employee ",
  "ehr_transferApplication_p_EmpType": "Staff classification",
  "ehr_transferApplication_p_OperateType": "Operation type",
  "ehr_transferApplication_p_MoveDate": "Transfer date",
  "ehr_transferApplication_p_Department": "Department transferred from /Current position",
  "ehr_transferApplication_p_TransferDepart": "Department transferred to /Post transferred to",
  "ehr_transferApplication_p_EmpLevel": "Level change",
  "ehr_transferApplication_p_PerformanceB": "Performance change",
  "ehr_transferApplication_p_WorkLocationB": "Current working location",
  "ehr_transferApplication_p_WorkLocationA": "Working location after transfer",
  "ehr_transferApplication_p_MoveReason": "Transfer reason",
  "ehr_transferApplication_p_ExtraRule": "Additional agreement",
  "ehr_transferApplication_p_BaseSalary": "Basic salary after transfer",
  "ehr_transferApplication_p_WealthSalary": "Caifu salary after transfer ",
  "ehr_transferApplication_p_TechSalary": "Skill-based salary after transfer ",
  "ehr_transferApplication_p_PlaceSubsidy": "Off-site work allowance",
  "ehr_transferApplication_p_MoveSubsidy": "Moving allowance",
  "ehr_transferApplication_p_HouseSubsidy": "Housing allowance",
  "ehr_transferApplication_p_GiveOutEndDate": "Last date of allowance payment",
  "ehr_transferApplication_btn_Pass": "Pass",
  "ehr_transferApplication_btn_AddCounter": "signer",
  "ehr_transferApplication_btn_Refuse": "Refuse",
  "ehr_transferApplication_btn_ReApplicant": "Return to the applicant",
  "ehr_transferApplication_btn_ReApproval": "Return to the previous",
  "ehr_transferApplication_label_select": "Please select",
  "ehr_transferApplication_jsalert_warn": "warn",
  "ehr_transferApplication_jsalert_Network": "no network",
  "ehr_transferApplication_jsalert_noAduiterList": "Approval flow is empty",
  "ehr_transferApplication_jstext_Status0": "Pending",
  "ehr_transferApplication_jstext_Status1": "Approved",
  "ehr_transferApplication_jstext_Status3": "Countersigned",
  "ehr_transferApplication_jstext_Status4": "Canceled",
  "ehr_transferApplication_jstext_Status5": "Canceled",
  "ehr_transferApplication_jsalert_success": "success",
  "ehr_transferApplication_jsalert_comment": "Please fill out your comments",
  "ehr_transferApplication_jsalert_ispass": "Are you sure you want approve?",
  "ehr_transferApplication_jsalert_isRefuse": "Are you sure you want refuse?",
  "ehr_transferApplication_jsalert_reason": "Please fill out your reason",
  "ehr_transferApplication_p_DQCBD": "Current Insured Land",
  "ehr_transferApplication_p_DDHCBD": "Insured Land after transfer",
  "ehr_transferApplication_p_BZ": "Currency",
  "ehr_transferApplication_p_JYXZYW": "Non-Competition Agreement required or not",
  "ehr_transferApplication_p_DRZX": "Group transferred to",
  "ehr_ContractCtrl_title": "Pending",
  "ehr_ContractCtrl_p_docutype": "Labor Contract Renew Application",
  "ehr_ContractCtrl_btn_refresh": "Refresh",
  "ehr_ContractCtrl_p_basicinfo": "Basic Info",
  "ehr_ContractCtrl_p_approvalinfo": "Approval Info",
  "ehr_ContractCtrl_p_process": "Workflow",
  "ehr_ContractCtrl_p_xqry": "Employee",
  "ehr_ContractCtrl_p_sqsj": "Time of application",
  "ehr_ContractCtrl_p_bm": "Department",
  "ehr_ContractCtrl_p_rzrq": "Date of Enrollment",
  "ehr_ContractCtrl_p_zj": "Rank",
  "ehr_ContractCtrl_p_htjsr": "End Date",
  "ehr_ContractCtrl_p_lshtxx": "All Labor Contracts Information",
  "ehr_ContractCtrl_p_qdcs": "Renewed Number of Times Since 2008",
  "ehr_ContractCtrl_p_ts": "Suggestion for new contract term",
  "ehr_ContractCtrl_p_cfxx": "Disciplinary Information",
  "ehr_ContractCtrl_p_jkzt": "Health Status",
  "ehr_ContractCtrl_p_ygfl": "Classification",
  "ehr_ContractCtrl_p_gsxx": "Work Injury Information",
  "ehr_ContractCtrl_p_zysx": "Matters requiring attention",
  "ehr_ContractCtrl_label_htlx": "Type for the new contract",
  "ehr_ContractCtrl_label_sfxq": "Renew or not",
  "ehr_ContractCtrl_label_xqnx": "Term of the renewed contract",
  "ehr_ContractCtrl_label_jyxzqd": "Signing non-competition clause",
  "ehr_ContractCtrl_label_htgs": "Employer",
  "ehr_ContractCtrl_label_xqgw": "Position",
  "ehr_ContractCtrl_label_xqgslx": "Working hours system",
  "ehr_ContractCtrl_label_xqhtzzr": "Expiration of the renewed contract",
  "ehr_ContractCtrl_label_xqhdsl": "Length of service after contact renewal",
  "ehr_ContractCtrl_label_bz": "Remarks",
  "ehr_ContractCtrl_btn_tg": "Pass",
  "ehr_ContractCtrl_btn_hqr": "signer",
  "ehr_ContractCtrl_btn_jj": "Refuse",
  "ehr_ContractCtrl_btn_thsqr": "Return to the applicant",
  "ehr_ContractCtrl_btn_thsyj": "Return to the previous",
  "ehr_ContractCtrl_btn_qx": "Cancel",
  "ehr_ContractCtrl_p_xzhtgs": "select Employer",
  "ehr_ContractCtrl_p_xzxqgw": "select Position",
  "ehr_ContractCtrl_jsalert_warn": "warn",
  "ehr_ContractCtrl_jsalert_Network": "no network",
  "ehr_ContractCtrl_jsalert_noAduiterList": "Approval flow is empty",
  "ehr_ContractCtrl_jstext_Status0": "Pending",
  "ehr_ContractCtrl_jstext_Status1": "Approved",
  "ehr_ContractCtrl_jstext_Status3": "Countersigned",
  "ehr_ContractCtrl_jstext_Status4": "Canceled",
  "ehr_ContractCtrl_jstext_Status5": "Canceled",
  "ehr_ContractCtrl_jsalert_confirm": "Confirm",
  "ehr_ContractCtrl_jsalert_success": "success",
  "ehr_ContractCtrl_jsalert_ispass": "Are you sure you want approve?",
  "ehr_ContractCtrl_jsalert_isRefuse": "Are you sure you want refuse?",
  "ehr_ContractCtrl_jsalert_comment": "Please fill out your comments",
  "ehr_ContractCtrl_jsalert_reason": "Please fill out your reason",
  "ehr_ContractCtrl_jsdate_Jan": "Jan",
  "ehr_ContractCtrl_jsdate_Feb": "Feb",
  "ehr_ContractCtrl_jsdate_Mar": "Mar",
  "ehr_ContractCtrl_jsdate_Apr": "Apr",
  "ehr_ContractCtrl_jsdate_May": "May",
  "ehr_ContractCtrl_jsdate_June": "June",
  "ehr_ContractCtrl_jsdate_July": "July",
  "ehr_ContractCtrl_jsdate_Aug": "Aug",
  "ehr_ContractCtrl_jsdate_Sep": "Sep",
  "ehr_ContractCtrl_jsdate_Oct": "Oct",
  "ehr_ContractCtrl_jsdate_Nov": "Nov",
  "ehr_ContractCtrl_jsdate_Dec": "Dec",
  "ehr_ContractCtrl_jsdate_Sun": "S",
  "ehr_ContractCtrl_jsdate_Mon": "M",
  "ehr_ContractCtrl_jsdate_Tues": "T",
  "ehr_ContractCtrl_jsdate_Wed": "W",
  "ehr_ContractCtrl_jsdate_Thur": "T",
  "ehr_ContractCtrl_jsdate_Fri": "F",
  "ehr_ContractCtrl_jsdate_Sat": "S",
  "ehr_ContractCtrl_jsdate_selectDate": "select date",
  "ehr_ContractCtrl_jsdate_todayLabel": "Today",
  "ehr_ContractCtrl_jsalert_NXYHTLX": "Type of contract to be renewed",
  "ehr_ContractCtrl_jsalert_SFXQ": "Whether to renew the contract",
  "ehr_ContractCtrl_jsalert_XQNX": "The length of contract renewal",
  "ehr_ContractCtrl_jsalert_JYXZQD": "Whether to sign non-competition clause",
  "ehr_ContractCtrl_jsalert_XQGW": "Please select the Position",
  "ehr_ContractCtrl_jsalert_HTGS": "Please select the Employer",
  "ehr_ContractCtrl_jsalert_XQGSLX": "Type of working hour system",
  "ehr_ContractCtrl_jsalert_XQHTZZR": "Termination date of renewed contract",
  "ehr_ContractCtrl_jsalert_BZ": "Please fill out your Remarks",
  "ehr_ContractCtrl_label_select": "Please select",
  "ehr_ContractCtrl_label_number": "number",
  "ehr_ContractCtrl_label_name": "name",
  "ehr_punish_title": "Pending",
  "ehr_punish_p_CFYGSQS": "Disciplanary Action Application",
  "ehr_punish_btn_refresh": "Refresh",
  "ehr_punish_p_basicinfo": "Basic Info",
  "ehr_punish_p_process": "Workflow",
  "ehr_punish_p_CFYG": "Employee to be disciplined",
  "ehr_punish_p_SQSJ": "Time of application",
  "ehr_punish_p_BM": "Department",
  "ehr_punish_p_ZJ": "Rank",
  "ehr_punish_p_SQCFDJ": "Discipline level",
  "ehr_punish_p_ZGLD": "Supervisor/leader",
  "ehr_punish_p_CFSY": "Discipline reason",
  "ehr_punish_p_CFYJ": "Basis for discipline",
  "ehr_punish_p_CFYJIAN": "Remarks",
  "ehr_punish_p_CFGZSH": "Discipline notification number",
  "ehr_punish_btn_SC": "Notification number generated.",
  "ehr_punish_btn_Pass": "Pass",
  "ehr_punish_btn_AddCounter": "signer",
  "ehr_punish_btn_Refuse": "Refuse",
  "ehr_punish_btn_ReApplicant": "Return to the applicant",
  "ehr_punish_btn_ReApproval": "Return to the previous",
  "ehr_punish_jsalert_warn": "warn",
  "ehr_punish_jsalert_Network": "no network",
  "ehr_punish_jsalert_noAduiterList": "Approval flow is empty",
  "ehr_punish_jstext_Status0": "Pending",
  "ehr_punish_jstext_Status1": "Approved",
  "ehr_punish_jstext_Status3": "Countersigned",
  "ehr_punish_jstext_Status4": "Canceled",
  "ehr_punish_jstext_Status5": "Canceled",
  "ehr_punish_jsalert_ispass": "Are you sure you want approve?",
  "ehr_punish_jsalert_cancel": "Cancel",
  "ehr_punish_jsalert_confirm": "Confirm",
  "ehr_punish_jsalert_success": "success",
  "ehr_punish_jsalert_comment": "Please fill out your comments",
  "ehr_punish_jsalert_isRefuse": "Are you sure you want refuse?",
  "ehr_punish_jsalert_reason": "Please fill out your reason",
  "ehr_punishCancel_p_CXCFSQS": "Application for Discipline Revocation",
  "ehr_punishCancel_p_CXYJ": "Basis of revocation",
  "ehr_AdjustmentApplication_title": "Pending",
  "ehr_AdjustmentApplication_btn_refresh": "Refresh",
  "ehr_AdjustmentApplication_p_docutype": "Application for salary or level adjustment",
  "ehr_AdjustmentApplication_p_basicinfo": "Basic Info",
  "ehr_AdjustmentApplication_p_process": "Workflow",
  "ehr_AdjustmentApplication_p_AdjustmentEmp": "Employee",
  "ehr_AdjustmentApplication_p_MoveDate": "Date of adjustment",
  "ehr_AdjustmentApplication_p_Department": "Department/Post ",
  "ehr_AdjustmentApplication_p_EmpLevel": "Post rank change",
  "ehr_AdjustmentApplication_p_PerformanceB": "Performance change",
  "ehr_AdjustmentApplication_p_applicant": "Applicant",
  "ehr_AdjustmentApplication_p_applyDate": "Time of application",
  "ehr_AdjustmentApplication_p_BaseSalary": "Basic Pay",
  "ehr_AdjustmentApplication_p_WealthSalary": "Caifu salary",
  "ehr_AdjustmentApplication_p_TechSalary": "Skill-based Pay",
  "ehr_AdjustmentApplication_p_Remark": "Remarks",
  "ehr_AdjustmentApplication_p_IncompetentPost": "incompetence change or not",
  "ehr_AdjustmentApplication_p_BZ": "Currency",
  "ehr_seal_p_docutype": "HR stamp",
  "ehr_seal_p_sealcompany": "Company using the stamp",
  "ehr_seal_p_sealfiletype": "Documents which can be stamped",
  "ehr_seal_p_sealuse": "Uses of the stamp",
  "ehr_seal_p_remak": "Remarks",
  "ehr_seal_p_warning": "Note",
  "ehr_overtime_title": "Overtime Application Form",
  "ehr_overtime_span_1": "Date of overtime",
  "ehr_overtime_span_2": "Overtime date",
  "ehr_overtime_span_3": "Hours",
  "ehr_overtime_span_4": "Reason for overtime",
  "ehr_overtime_span_5": "Working attendance",
  "ehr_overtime_span_6": " has already applied for ",
  "ehr_overtime_span_7": " hour(s) of overtime",
  "ehr_overtime_span_8": "No Information",
  "ehr_regular_title": "Pending",
  "ehr_regular_p_docutype": "Trial Staff Appraisal Form",
  "ehr_regular_p_regularUser": "Regular Employees",
  "ehr_regular_span_1": "Whether to give positive",
  "ehr_regular_span_2": "Self-assessment",
  "ehr_regular_span_3": "Business Knowledge",
  "ehr_regular_span_4": "a.Working knowledge and operational capacity",
  "ehr_regular_span_5": "b.Comprehend and accept new knowledge capacity",
  "ehr_regular_span_6": "Work attitude",
  "ehr_regular_span_7": "a.Enthusiasm towards work and enterprising",
  "ehr_regular_span_8": "b.Able to cope with the extra work pressure Ability to cope with work pressure",
  "ehr_regular_span_9": "Work ability",
  "ehr_regular_span_10": "a.Ability to control the pace of work",
  "ehr_regular_span_11": "b.Comprehend and complete assigned work",
  "ehr_regular_span_12": "Job performance",
  "ehr_regular_span_13": "a.implementation deadline for completion of work ",
  "ehr_regular_span_14": "b.Ability to perform creative work done Ability to finish the job full of creativity",
  "ehr_regular_span_15": "Teamwork",
  "ehr_regular_span_16": "a.Company dedication and loyalty",
  "ehr_regular_span_17": "b.Whether others trust and mutual encouragement",
  "ehr_regular_span_18": "c.Whether to live in harmony with colleagues and leadership",
  "ehr_regular_span_19": "d.Centripetal force and sense of responsibility of the department",
  "ehr_regular_span_20": "Opinion",
  "ehr_regular_span_21": "Positive information(Skill-based Pay applies only to 'S' series employees.)",
  "ehr_regular_span_22": "Current Basic Pay",
  "ehr_regular_span_23": "Current Skill-based Pay",
  "ehr_regular_span_24": "Regular Basic Salary by the Agreement",
  "ehr_regular_span_25": "Regular Agreement before Employee Reports",
  "ehr_regular_span_26": "Filled in by Supervisor",
  "ehr_regular_span_27": "Regular Basic",
  "ehr_regular_span_28": "Regular Skill-based Pay",
  "ehr_regular_span_29": "Currency",
  "ehr_regular_span_30": "Regular Rank",
  "ehr_regular_span_31": "Filled in by HR",
  "ehr_regular_span_32": "Formaldate",
  "ehr_regular_span_33": "Options Form of Payment",
  "ehr_regular_span_34": "KPI",
  "ehr_regular_alert_0": "Please select regular",
  "ehr_regular_alert_1": "Please fill out Self-assessment",
  "ehr_regular_alert_2": "Please select business knowledge",
  "ehr_regular_alert_3": "Please select business knowledge",
  "ehr_regular_alert_4": "Please select work attitude",
  "ehr_regular_alert_5": "Please select work attitude",
  "ehr_regular_alert_6": "Please select work ability",
  "ehr_regular_alert_7": "Please select work ability",
  "ehr_regular_alert_8": "Please select job performance",
  "ehr_regular_alert_9": "Please select job performance",
  "ehr_regular_alert_10": "Please select teamwork",
  "ehr_regular_alert_11": "Please select teamwork",
  "ehr_regular_alert_12": "Please select teamwork",
  "ehr_regular_alert_13": "Please select teamwork",
  "ehr_regular_alert_14": "Please fill out total score",
  "ehr_regular_alert_15": "Please fill out opinion",
  "ehr_regular_alert_16": "Please fill out current basic pay",
  "ehr_regular_alert_17": "Please fill out current skill-based pay",
  "ehr_regular_alert_18": "Please fill out regular basic salary by the agreement",
  "ehr_regular_alert_19": "Please fill out regular agreement beofore employee reports",
  "ehr_regular_alert_20": "Please fill out regular basic",
  "ehr_regular_alert_21": "Please fill out regular skill-based pay",
  "ehr_regular_alert_22": "Please select currency",
  "ehr_regular_alert_23": "Please select regular rank",
  "ehr_regular_alert_24": "Please fill out formaldate",
  "ehr_regular_alert_25": "Please select options Ffrm of payment",
  "ehr_regular_alert_26": "Please select KPI",
  "oa_alert_response_null": "Network connection exception, please check your network!",
  "oa_error_status_403": "Access Denied",
  "oa_error_system_info": "Server Exception",
  "oa_error_status_1001": "Http request not post method",
  "oa_error_status_1002": "URL is invaild",
  "oa_error_status_1003": "Access_token is missing",
  "oa_error_status_1004": "Access_token is invaild",
  "oa_error_status_1005": "Access_token is expired",
  "oa_error_status_1006": "Service code has not registered",
  "oa_error_status_1007": "AccessToken has not permission to access",
  "oa_error_status_1008": "SOA Malformed URL",
  "oa_error_status_1009": "Token openid and openkey auth failed",
  "oa_error_status_1010": "Create token failed ,token not exists in database",
  "oa_error_status_1011": "Refresh token failed ,token not exists in database",
  "oa_error_status_400": "Service Host is invalid",
  "oa_error_status_406": "Limited max concurrent requests",
  "oa_error_status_408": "Connection time out",
  "oa_error_status_504": "Socket time out",
  "OA_fixedassertallocationdetail_text_model": "Model",
  "OA_oneCommit_warning": "No repeat submission!",
  "oa_copy_success": "Copy to the clipboard success",
  "OA_costaccountdetail_text_overtime": "Traffic Expense",
  "OA_costaccountdetail_text_workinghours": "Attendance Record",
  "oa_yes": "yes",
  "oa_no": "no",
  "OA_text_usedate": "Date of application",
  "OA_Salary_text_unitprice": "Application amount",
  "OA_Salary_text_residualvalue": "Actual amount",
  "OA_text_payment_payee": "Receiving unit(person)",
  "OA_travel_card_reimbursement": "Travel card reimbursement",
  "ehr_Intern_p_SXSLYSQPGB": "实习生留用申请评估表",
  "ehr_Intern_p_basicinfo": "基本信息",
  "ehr_Intern_p_process": "审批流程",
  "ehr_Intern_p_SXS": "实习生",
  "ehr_Intern_p_SQSJ": "申请时间",
  "ehr_Intern_p_SQBM": "申请部门",
  "ehr_Intern_p_DSYG": "导师员工",
  "ehr_Intern_p_GW": "岗位",
  "ehr_Intern_p_RZRQ": "入职日期",
  "ehr_Intern_p_SJGZSJ": "实际工作时间",
  "ehr_Intern_p_QZRQ": "最高学历起止时间",
  "ehr_Intern_p_XXMC": "学校名称",
  "ehr_Intern_p_ZY": "专业",
  "ehr_Intern_p_XLLX": "学历类型",
  "OA_item_total_amount": "Total amount of the project",
  "OA_recipient_itemdetail_text_item": "Payee",
  "OA_recipient_itemdetail_text_account": "Recipient Account",
  "OA_recipient_itemdetail_text_bankName": "Bank Name",
  "OA_recipient_itemdetail_text_city": "Bank City",
  "OA_recipient_itemdetail_text_cashPledgeAmount": "Deposit Payment",
  "OA_recipient_itemdetail_text_contractPaymentAmount": "Payment Amount",
  "OA_additemdetail_text_paymentdetail": "Payment Details",
  "OA_itemDetail_text_recipientAccountNumber": "Account of Receiving Unit",
  "OA_itemDetail_text_contractPaymentAmount": "Payment amount",
  "OA_no_Down_Title": 'Unable to download',
  "OA_no_Down_Tips": 'This file format is not supported on mobile phone, please download it on PC.',
  "OA_detail_business_type": 'Business group',
  "OA_detail_business_type_placeholder": 'Business group query', 
}

module.exports = {
  lang_ZH: lang_ZH,
  lang_EN: lang_EN,
}